import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const d=JSON.parse(readFileSync('data/knowledge/epigenome-structures.json'));
test('all epigenome calls match parent bases, valid inclusive spans and non-overlapping sites',()=>{const used=new Set();for(const c of d.exampleCalls){const m=d.modifications.find(m=>m.id===c.modification);assert.ok(m);const span=c.span||1;assert.ok(c.position>=1&&c.position+span-1<=d.sequence.sequence.length);assert.ok(m.base.split('/').includes(d.sequence.sequence.slice(c.position-1,c.position-1+span)),m.id);for(let i=c.position;i<c.position+span;i++){assert.ok(!used.has(i));used.add(i);}}});
test('idealized helix pairs cover the teaching sequence with complementary bases',()=>{const mate={A:'T',C:'G',G:'C',T:'A'};assert.equal(d.helix.length,d.sequence.sequence.length*2);for(let i=1;i<=d.sequence.sequence.length;i++){const a=d.helix.find(p=>p.position===i&&p.strand===1),b=d.helix.find(p=>p.position===i&&p.strand===2);assert.equal(a.base,d.sequence.sequence[i-1]);assert.equal(b.base,mate[a.base]);for(const p of [a,b])for(const k of ['x','y','z'])assert.ok(Number.isFinite(p[k]));}});
test('track and contact bins cover full sequence without gaps and preserve zero-based matrix dimensions',()=>{for(const t of [...d.tracks,d.hic]){assert.equal(t.bins[0].start,1);assert.equal(t.bins.at(-1).end,d.sequence.sequence.length);t.bins.forEach((b,i)=>{assert.ok(b.end>=b.start);if(i)assert.equal(b.start,t.bins[i-1].end+1);});}for(const t of d.tracks){assert.equal(t.bins.length,t.values.length);assert.ok(t.values.every(v=>Number.isFinite(v)&&v>=0));}assert.equal(d.hic.matrix.length,d.hic.size);d.hic.matrix.forEach((row,i)=>{assert.equal(row.length,d.hic.size);row.forEach((v,j)=>assert.equal(v,d.hic.matrix[j][i]));});});
test('original epigenome materials are preserved and unverified SMILES withheld',()=>{const audit=JSON.parse(readFileSync('data/provenance/epigenome-import-audit.json'));for(const f of audit.files)assert.equal(createHash('sha256').update(readFileSync(f.preserved_path)).digest('hex'),f.sha256);assert.equal(d.modifications.length,18);for(const m of d.modifications){assert.equal(m.smiles,'');assert.ok(m.structureStatus.includes('not verified'));assert.ok(m.roles.length&&m.enzymes.length&&m.assays.length);}});
