"use client";
import {useState} from 'react';
import catalog from '@/data/catalog/datasets.json';
import {inspectData} from '@/lib/data-import';
import type {DataCategory} from '@/lib/data-catalog';
import {useDataSession} from './data-session';
import {Button} from './ui/button';
export function CatalogLibrary(){const {datasets,add}=useDataSession();const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const records=catalog.datasets.filter(d=>`${d.title} ${d.filename} ${d.category} ${d.collection}`.toLowerCase().includes(query.toLowerCase()));
 async function load(d:typeof catalog.datasets[number]){if(busy)return;setBusy(true);try{if(datasets.some(x=>x.id==='v5:'+d.id)){setMessage('This catalog dataset is already loaded.');return;}if(datasets.length>=40)throw Error('Remove a session file before adding another (40-file limit).');const r=await fetch(d.public_path);if(!r.ok)throw Error('Could not load this dataset. Please reload and try again.');const content=await r.text(),bytes=new Blob([content]).size;if(bytes>5*1024*1024||datasets.reduce((s,x)=>s+x.bytes,0)+bytes>20*1024*1024)throw Error('Dataset exceeds the current session size limit. Download it for external analysis.');const report=inspectData(d.filename,content,d.category as DataCategory);add([{...report,id:'v5:'+d.id,name:'Catalog · '+d.filename,bytes,source:'sample'}]);setMessage(d.title+': '+report.message);}catch(e){setMessage(e instanceof Error?e.message:'Cannot load dataset');}finally{setBusy(false);}}
 return <section className="catalog-library"><div className="data-section-title"><div><h2>Integrated archive catalog</h2><p>36 original datasets from the uploaded version, including legacy spectra and structure files. Downloads preserve their original bytes.</p></div></div><label className="data-search">Find a catalog dataset<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by title, file, omics layer or collection"/></label>{message&&<p role="status" className="data-notice">{message}</p>}<div className="data-samples">{records.map(d=><article key={d.id}><span className="data-eyebrow">{d.collection} · {d.category}</span><h3>{d.title}</h3><p>{d.description}</p><code>{d.filename}</code><small>{d.units}</small><div><Button disabled={busy} onClick={()=>void load(d)}>Load dataset</Button><a href={d.public_path} download>Download original</a></div></article>)}</div>{!records.length&&<p>No catalog datasets match this search.</p>}</section>;
}
