"use client";
import { useRef, useState } from 'react';
import Link from 'next/link';
import { Button } from './ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from './ui/tabs';
import { HIERARCHY_GROUPS, HIERARCHY_NODES } from '@/lib/biological-hierarchy';
import { HIERARCHY_TEMPLATES, MOLECULE_LOCATIONS, rowsWithColumns, sameSample, finiteCoordinate, type JoinedRow } from '@/lib/hierarchy-data';
import { inspectData } from '@/lib/data-import';
import { useDataSession } from './data-session';
import { NucleobasePanel } from './nucleobase-viewer';
import { HierarchicalBiologyPanel } from './hierarchical-biology-panel';

function CoordinateView({rows}:{rows:JoinedRow[]}) {
 const [angle,setAngle]=useState(35);const [tilt,setTilt]=useState(15);const [zoom,setZoom]=useState(1);const [point,setPoint]=useState(0);
 const units=[...new Set(rows.map(r=>r.unit))];
 if(!rows.length)return <Missing kind="3D coordinates" fields="participant_id, sample_id, molecule, point_id, x, y, z, unit, resolution"/>;
 if(units.length!==1)return <p className="data-notice">These coordinates have mixed units. Select or export a single coordinate system before plotting.</p>;
 const centers=['x','y','z'].map(k=>rows.reduce((sum,r)=>sum+Number(r[k]),0)/rows.length);
 const scale=100/Math.max(1,...rows.flatMap(r=>['x','y','z'].map((k,i)=>Math.abs(Number(r[k])-centers[i]))));
 const points=rows.map((r,i)=>{const [x,y,z]=['x','y','z'].map((k,j)=>Number(r[k])-centers[j]);const a=angle*Math.PI/180,b=tilt*Math.PI/180;const xx=x*Math.cos(a)+z*Math.sin(a),zz=-x*Math.sin(a)+z*Math.cos(a);return {i,x:260+xx*scale*zoom,y:155+(y*Math.cos(b)-zz*Math.sin(b))*scale*zoom,z:zz};}).sort((a,b)=>a.z-b.z);
 const chosen=rows[Math.min(point,rows.length-1)];
 return <div className="molecular-3d"><p className="data-notice">Coordinate point cloud · {units[0]}. {rows.some(r=>r.resolution.includes('teaching'))?'Synthetic coarse teaching points, not atoms, bonds, or a predicted fold.':'Resolution is supplied by the file; bonds and chemical validity are not inferred.'}</p><svg viewBox="0 0 520 310" role="img" aria-label="Rotatable projection of supplied 3D coordinates">{points.map(p=><g key={p.i}><circle cx={p.x} cy={p.y} r={p.i===point?9:6} fill={p.i===point?'#ffc66d':'#74dfc7'} onClick={()=>setPoint(p.i)} role="button" tabIndex={0} aria-label={'Select point '+rows[p.i].point_id} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setPoint(p.i)}}}/><text x={p.x+10} y={p.y+4} fill="#c7dce7" fontSize="12">{rows[p.i].point_id}</text></g>)}</svg><div className="molecule-controls"><label>Rotate {angle}°<input type="range" min="-180" max="180" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></label><label>Tilt {tilt}°<input type="range" min="-90" max="90" value={tilt} onChange={e=>setTilt(Number(e.target.value))}/></label><label>Zoom {zoom.toFixed(1)}×<input type="range" min="0.5" max="1.2" step="0.1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></div><p>Selected point <strong>{chosen.point_id}</strong>: x = {chosen.x}, y = {chosen.y}, z = {chosen.z}. Resolution: {chosen.resolution}.</p><p className="data-help">Source: {[...new Set(rows.map(r=>r._file))].join(', ')}</p></div>;
}
function Missing({kind,fields}:{kind:string;fields:string}) {return <div className="data-empty"><h3>No {kind} for this sample</h3><p>No values or structures have been inferred.</p><p>Provide columns: <code>{fields}</code>.</p><Link className="data-open" href="/explore/loader">Upload matching data or load a sample →</Link></div>;}
function TimeView({rows}:{rows:JoinedRow[]}) {
 const [index,setIndex]=useState(0);
 const ordered=rows.filter(r=>r.time_hours?.trim()&&r.value?.trim()&&Number.isFinite(Number(r.time_hours))&&Number.isFinite(Number(r.value))).sort((a,b)=>Number(a.time_hours)-Number(b.time_hours));
 if(!ordered.length)return <Missing kind="time-course measurements" fields="participant_id, sample_id, molecule, time_hours, value, unit"/>;
 if(new Set(ordered.map(r=>r.unit)).size>1 || new Set(ordered.map(r=>r.time_hours)).size!==ordered.length)return <p className="data-notice">Multiple units or replicate values occur at the same time. Export one comparable series per molecule and sample before plotting; replicates are not averaged automatically.</p>;
 const current=ordered[Math.min(index,ordered.length-1)],minT=Number(ordered[0].time_hours),maxT=Number(ordered.at(-1)!.time_hours),minV=Math.min(...ordered.map(r=>Number(r.value))),maxV=Math.max(...ordered.map(r=>Number(r.value)));
 const x=(r:JoinedRow)=>45+(Number(r.time_hours)-minT)/(maxT-minT||1)*420,y=(r:JoinedRow)=>210-(Number(r.value)-minV)/(maxV-minV||1)*155;
 return <div><p className="data-notice">Time dimension (“4D”): recorded measurements over time. This is not a molecular-dynamics trajectory or an animated 3D structure.</p><svg className="molecule-timeplot" viewBox="0 0 520 265" role="img" aria-label="Molecular measurement over time"><line x1="45" x2="465" y1="210" y2="210" stroke="#557380"/>{ordered.map((r,i)=><g key={i}><circle cx={x(r)} cy={y(r)} r={i===index?8:5} fill={i===index?'#ffc66d':'#74dfc7'}/><text x={x(r)} y="235" textAnchor="middle" fill="#bbd5df" fontSize="12">{r.time_hours} h</text><text x={x(r)} y={y(r)-14} textAnchor="middle" fill="#bbd5df" fontSize="12">{r.value}</text></g>)}<text x="260" y="258" fill="#bbd5df" fontSize="12" textAnchor="middle">Time (hours); values in {current.unit}</text></svg><label>Time point: {current.time_hours} hours<input className="molecule-time-slider" type="range" min="0" max={ordered.length-1} value={Math.min(index,ordered.length-1)} onChange={e=>setIndex(Number(e.target.value))}/></label><p>Value: <strong>{current.value} {current.unit}</strong> · Source: {current._file}</p><p className="data-help">For single-cell assays, destructive assays generally cannot follow the same cell repeatedly. These fictional time points are teaching data, not evidence of longitudinal sampling of a living cell.</p></div>;
}
export function HierarchyExplorer() {
 const {datasets,add}=useDataSession();const [person,setPerson]=useState('');const [sample,setSample]=useState('');const [molecule,setMolecule]=useState('dna');const [position,setPosition]=useState(0);const [notice,setNotice]=useState('');const [legacy,setLegacy]=useState(false);const detail=useRef<HTMLElement>(null);
 const metadata=rowsWithColumns(datasets,['participant_id','sample_id','tissue','cell_type','assay_mode','cell_id']).filter(r=>r.participant_id&&r.sample_id);
 const participants=[...new Set(metadata.map(r=>r._origin+':'+r.participant_id))];const activePerson=participants.includes(person)?person:participants[0]||'';
 const specimens=metadata.filter(r=>r._origin+':'+r.participant_id===activePerson);const selected=specimens.find(r=>r._dataset+':'+r.sample_id===sample)||specimens[0];
 const node=HIERARCHY_NODES[molecule];
 const allSequences=rowsWithColumns(datasets,['participant_id','sample_id','molecule','sequence']);const allCoords=rowsWithColumns(datasets,['participant_id','sample_id','molecule','point_id','x','y','z','unit','resolution']);const allTimes=rowsWithColumns(datasets,['participant_id','sample_id','molecule','time_hours','value','unit']);
 const matches=(r:JoinedRow)=>!!selected&&sameSample(r,selected,molecule)&&r._origin===selected._origin;
 const sequences=allSequences.filter(matches);const coordinates=allCoords.filter(matches).filter(finiteCoordinate);const timeline=allTimes.filter(matches);
 const sequence=sequences.length===1?sequences[0].sequence:'';const pos=Math.min(position,Math.max(0,sequence.length-1));
 function choose(id:string){setMolecule(id);setPosition(0);requestAnimationFrame(()=>detail.current?.scrollIntoView({behavior:'smooth',block:'start'}));}
 function load(){const fresh=HIERARCHY_TEMPLATES.filter(t=>!datasets.some(d=>d.source==='sample'&&d.name===t.filename));if(datasets.length+fresh.length>40){setNotice('Remove some session files before loading the hierarchy examples.');return;}add(fresh.map(t=>({...inspectData(t.filename,t.content,t.category),id:crypto.randomUUID(),name:t.filename,bytes:new Blob([t.content]).size,source:'sample' as const})));setNotice('Hierarchy teaching data loaded: two fictional participants, three specimens, seven molecular layers.');}
 return <div className="hierarchy-explorer"><header className="data-hub-header"><div><span className="data-eyebrow">PARTICIPANT · SPECIMEN · CELL · MOLECULE</span><h1>Hierarchical molecular explorer</h1><p>Choose a specimen, then open a molecular layer to inspect its evidence.</p></div><Button onClick={load}>Load hierarchy samples</Button></header>{notice&&<p className="data-notice" role="status">{notice}</p>}
 <div className="hierarchy-context"><label>Participant<select value={activePerson} onChange={e=>{setPerson(e.target.value);setSample('');setPosition(0)}}><option value="" disabled>No participant metadata</option>{participants.map(p=><option key={p} value={p}>{p.split(':').slice(1).join(':')} ({p.startsWith('sample:')?'fictional sample':'uploaded'})</option>)}</select></label><label>Specimen / cell<select value={selected?selected._dataset+':'+selected.sample_id:''} onChange={e=>{setSample(e.target.value);setPosition(0)}}><option value="" disabled>No specimen metadata</option>{specimens.map((s,i)=><option key={i} value={s._dataset+':'+s.sample_id}>{s.sample_id} · {s.tissue} · {s.assay_mode}</option>)}</select></label><Link className="data-open" href="/explore/loader">Upload molecular files →</Link></div>
 {selected?<><div className="specimen-facts">{[['Participant',selected.participant_id],['Body location',selected.tissue||'Not supplied'],['Cell type',selected.cell_type||'Not supplied'],['Assay',selected.assay_mode||'Not supplied'],['Cell ID',selected.cell_id||'Not supplied']].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="data-notice">{selected._origin==='sample'?'Fictional participant and synthetic measurements. ':'Metadata supplied by the user; not independently verified. '}{selected.assay_mode==='bulk'?'Bulk data combines many cells; it cannot identify a measurement from an individual cell.':selected.assay_mode==='single-cell'?'Single-cell label supplied. Cell identity depends on the assay and annotation; single-cell RNA does not by itself measure DNA or protein.':'Assay mode is unrecognized; use bulk or single-cell in metadata.'}</p></>:<Missing kind="participant or tissue metadata" fields="participant_id, sample_id, tissue, cell_type, assay_mode, cell_id"/>}
 <div className="hierarchy-groups">{HIERARCHY_GROUPS.map(group=><section className="hierarchy-group-card" key={group.id}><h2>{group.title}</h2><div className="hierarchy-node-grid">{group.nodes.map(id=><button className={'hierarchy-node-button '+(molecule===id?'is-selected':'')} key={id} onClick={()=>choose(id)} aria-pressed={molecule===id} aria-controls="molecule-detail"><strong>{HIERARCHY_NODES[id].label}</strong><small>{HIERARCHY_NODES[id].subtitle}</small></button>)}</div></section>)}</div>
 <section id="molecule-detail" ref={detail} className="molecule-detail"><div className="data-section-title"><div><span className="data-eyebrow">MOLECULAR DETAIL PANEL</span><h2>{node.label}</h2></div><span className="scope-badge">{selected?selected.sample_id:'No sample assigned'}</span></div><p>{node.description}</p><p><strong>Typical cellular location: </strong>{MOLECULE_LOCATIONS[molecule]||'Depends on the assay and feature. This layer describes evidence or cellular context, not necessarily a discrete molecule.'}</p>
 <Tabs defaultValue="2d"><TabsList aria-label="Molecule views"><TabsTrigger value="2d">2D · sequence & features</TabsTrigger><TabsTrigger value="3d">3D · coordinates</TabsTrigger><TabsTrigger value="4d">4D · time</TabsTrigger><TabsTrigger value="context">Biology & provenance</TabsTrigger></TabsList>
 <TabsContent value="2d">{sequence?<><p>Sequence from {sequences[0]._file}; {sequence.length} symbols. Select a position.</p><div className="molecule-sequence">{sequence.split('').slice(0,200).map((base,i)=><button key={i} aria-pressed={pos===i} onClick={()=>setPosition(i)} className={pos===i?'active':''}><small>{i+1}</small>{base}</button>)}</div><p><strong>Position {pos+1}: {sequence[pos]}</strong>{['dna','rna'].includes(molecule)?` · Triplet ${Math.floor(pos/3)+1}: ${sequence.slice(Math.floor(pos/3)*3,Math.floor(pos/3)*3+3)} (frame 1 grouping only; coding frame is not inferred).`:' · Residue symbol; sequence does not establish a 3D fold.'}</p>{sequence.length>200&&<p>Showing the first 200 positions.</p>}<p>{molecule==='dna'?'DNA nucleotide: base + deoxyribose sugar + phosphate. Canonical base pairs are A–T and C–G.':molecule==='rna'?'RNA nucleotide: base + ribose sugar + phosphate. RNA uses uracil (U); sequence alone does not establish secondary structure.':'Peptide backbones contain repeating N–Cα–C units joined by peptide bonds; side chains differ between amino acids.'}</p></>:sequences.length>1?<p className="data-notice">Multiple sequences match this specimen and molecule. Export one target sequence per specimen/molecule for this panel; no sequence was chosen automatically.</p>:<Missing kind="linked sequence or feature data" fields="participant_id, sample_id, molecule, sequence"/>}{sequence && ["dna","rna"].includes(molecule) && <NucleobasePanel base={sequence[pos]} mode="2d" sample={selected?.sample_id||"unknown"} position={pos+1} polymer={molecule as "dna"|"rna"}/>}<div className="molecule-depth"><h3>Explore this layer</h3><ul>{node.structure2d.map(s=><li key={s}>{s}</li>)}</ul><p className="data-help">These are biological concepts, not inferred features of your sample.</p></div></TabsContent>
 <TabsContent value="3d">{sequence && ["dna","rna"].includes(molecule) && <NucleobasePanel base={sequence[pos]} mode="3d" sample={selected?.sample_id||"unknown"} position={pos+1} polymer={molecule as "dna"|"rna"}/>}<CoordinateView key={activePerson+sample+molecule} rows={coordinates}/>{allCoords.filter(matches).length>coordinates.length&&<p className="data-notice">Some coordinate rows were excluded because x, y or z is missing or nonnumeric.</p>}</TabsContent>
 <TabsContent value="4d"><TimeView key={activePerson+sample+molecule} rows={timeline}/></TabsContent>
 <TabsContent value="context"><h3>From person to molecular observation</h3><ol><li>Participant identifier: {selected?.participant_id||'not supplied'}.</li><li>Specimen and body location: {selected?.sample_id||'not supplied'}; {selected?.tissue||'not supplied'}.</li><li>Cell context: {selected?.cell_type||'not supplied'}; assay mode {selected?.assay_mode||'not supplied'}.</li><li>Molecular layer: {node.label}. Matching uses both participant_id and sample_id.</li><li>Available evidence: {sequences.length} sequence record(s), {coordinates.length} coordinate point(s), {timeline.length} time record(s).</li></ol><h3>Biological detail</h3><ul>{node.details.map(d=><li key={d}>{d}</li>)}</ul><p>No clinical interpretation, atom typing, folding, or cross-assay inference is performed. Tissue and cell type cannot be deduced reliably from a sequence filename.</p><p className="data-help">Only the first 200 preview rows of each imported file are available to this viewer. Export a focused participant/sample subset for larger datasets. Uploads are joined separately from built-in samples.</p></TabsContent>
 </Tabs></section><div className="data-section-title"><h2>Linked DNA → RNA → protein teaching model</h2><Button variant="outline" onClick={()=>setLegacy(v=>!v)}>{legacy?'Hide':'Open'} original model</Button></div>{legacy&&<HierarchicalBiologyPanel/>}</div>;
}
