'use client';
import {useState} from 'react';
import {contactMatrix,HIC_COLUMNS} from '@/lib/hierarchy-hic';
import {rowsWithColumns,type JoinedRow} from '@/lib/hierarchy-data';
import {useDataSession} from './data-session';
export function HierarchyHic({sample}:{sample?:JoinedRow}){
 const {datasets}=useDataSession();const [file,setFile]=useState(''),[selected,setSelected]=useState('');
 const rows=rowsWithColumns(datasets,HIC_COLUMNS).filter(r=>sample&&r.participant_id===sample.participant_id&&r.sample_id===sample.sample_id&&r._origin===sample._origin);
 const files=[...new Set(rows.map(r=>r._dataset))];const active=files.includes(file)?file:files[0];const data=rows.filter(r=>r._dataset===active);
 let matrix:ReturnType<typeof contactMatrix>|undefined,error='';try{if(data.length)matrix=contactMatrix(data);}catch(e){error=(e as Error).message;}
 return <section className="range-workspace"><h3>Participant-linked Hi-C contact map</h3><p>Hi-C uses genomic bins, independently of the short molecular sequence range. This map does not infer atomic coordinates or molecular motion.</p><a href="/data/hierarchy_hic.tsv" download>Download linked Hi-C template</a>{!rows.length?<p className="data-notice">No linked Hi-C contacts for this specimen. Click “Load hierarchy samples” for synthetic contacts, or upload the template with matching participant_id and sample_id. Generic Hi-C files without these identifiers cannot be assigned to a participant.</p>:<><label>Contact dataset<select value={active} onChange={e=>{setFile(e.target.value);setSelected('')}}>{files.map(id=><option key={id} value={id}>{rows.find(r=>r._dataset===id)?._file}</option>)}</select></label>{error?<p role="alert">{error}</p>:matrix&&<><p>{data[0].assembly} · {data[0].chrom} · {data[0].normalization} counts · 0-based, end-exclusive. {sample?._origin==='sample'?'Synthetic teaching data; not experimental patient results.':''}</p><div style={{overflowX:'auto'}}><table className="hic-linked-table"><caption>Contact counts. Color scale 0–{Math.max(1,...matrix.cells.values())}; — means missing, 0 means recorded zero.</caption><thead><tr><th>bp × bp</th>{matrix.bins.map(b=><th key={b.key}>{b.start}–{b.end}</th>)}</tr></thead><tbody>{matrix.bins.map(a=><tr key={a.key}><th>{a.start}–{a.end}</th>{matrix!.bins.map(b=>{const v=matrix!.cells.get([a.key,b.key].sort().join('|'));return <td key={b.key}><button aria-label={`${a.start}–${a.end} by ${b.start}–${b.end}: ${v??'missing'}`} onClick={()=>setSelected(`${a.start}–${a.end} × ${b.start}–${b.end}: ${v??'missing'} contacts`)} style={{background:v===undefined?'#172332':`rgba(29,190,162,${0.08+0.92*v/Math.max(1,...matrix!.cells.values())})`}}>{v??'—'}</button></td>})}</tr>)}</tbody></table></div><p role="status">{selected||'Select a contact to inspect its genomic intervals.'}</p></>}</>}</section>;
}
