'use client';
import {useState} from 'react';
import {type JoinedRow} from '@/lib/hierarchy-data';
export function HierarchyEvidence({rows}:{rows:JoinedRow[]}){
 const [query,setQuery]=useState('');const filtered=rows.filter(r=>[r.feature_id,r.measurement,r.details].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <section className="range-workspace"><h3>Linked observations & annotations</h3><a href="/data/hierarchy_evidence.tsv" download>Download linked observations template</a><p>Each row belongs to the selected participant and specimen. Network edges, spatial positions and imaging measurements are supplied annotations; exact structures, raw images and inferred results are not generated from these values.</p>{!rows.length?<p className="data-notice">No linked observations for this layer and specimen. Load hierarchy samples or upload matching participant_id, sample_id and molecule columns. Single-cell examples are attached to blood_T01; spatial examples to liver_bulk. Unsupported combinations remain empty.</p>:<><label>Find a feature<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Feature, measurement or annotation"/></label><p>{filtered.length} of {rows.length} observations. {rows.every(r=>r._origin==='sample')?'All values are synthetic teaching data.':rows.every(r=>r.evidence?.startsWith('public experimental:'))?'Public experimental measurements from TCGA via cBioPortal; processed values are not clinical interpretations.':'Uploaded annotations have not been independently verified.'}</p><ObservationBars rows={filtered}/><div style={{overflowX:'auto'}}><table className="hic-linked-table"><thead><tr><th>Feature / edge</th><th>Measurement</th><th>Value</th><th>Unit</th><th>Details</th><th>Evidence / source</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r._dataset+':'+i}><td>{r.feature_id}</td><td>{r.measurement}</td><td>{r.value}</td><td>{r.unit}</td><td>{r.details}</td><td>{r.evidence}<br/>{r._file}</td></tr>)}</tbody></table></div>{!filtered.length&&<p>No matches. Clear the search to see all linked observations.</p>}</>}</section>;
}

function ObservationBars({rows}:{rows:JoinedRow[]}){
 const finite=rows.filter(r=>r.value?.trim()!==''&&Number.isFinite(Number(r.value)));
 if(!finite.length||new Set(finite.map(r=>r.unit)).size!==1)return null;
 const shown=finite.slice(0,30),min=Math.min(0,...shown.map(r=>Number(r.value))),max=Math.max(0,...shown.map(r=>Number(r.value))),span=max-min||1;
 const x=(v:number)=>170+(v-min)/span*360;
 return <><h4>Measured values</h4><p>{shown[0].unit}. One scale within this panel; RNA and protein units are not interchangeable. {finite.length>30?'Showing the first 30 matching values; the table retains all matches.':''}</p><svg viewBox={`0 0 700 ${shown.length*42+45}`} role="img" aria-label="Feature measurements on a linear scale with zero baseline" style={{width:'100%',maxWidth:850}}><line x1={x(0)} x2={x(0)} y1="8" y2={shown.length*42+8} stroke="#9db1c0"/>{shown.map((r,i)=><g key={i}><text x="5" y={i*42+29} fill="currentColor" fontSize="14">{r.feature_id.slice(0,20)}</text><rect x={Math.min(x(0),x(Number(r.value)))} y={i*42+12} width={Math.max(1,Math.abs(x(Number(r.value))-x(0)))} height="22" fill={Number(r.value)<0?'#f0b35a':'#45bdad'}/><text x="550" y={i*42+29} fill="currentColor" fontSize="14">{r.value}</text><title>{r.feature_id}: {r.value} {r.unit}</title></g>)}<text x="170" y={shown.length*42+35} fill="currentColor" fontSize="13">{min}</text><text x="530" y={shown.length*42+35} textAnchor="end" fill="currentColor" fontSize="13">{max}</text></svg></>;
}
