"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Button} from './ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './ui/tabs';
import {ProteinAtomScene} from './protein-atom-scene';
import {useDataSession} from './data-session';
import {metaboliteSamples,moleculeScene,validateMolecule,type Molecule} from '@/lib/metabolite-structures';
const COLORS:Record<string,string>={C:'#a8c1d4',O:'#fb7185',N:'#60a5fa',P:'#fb923c',S:'#facc15',H:'#f8fafc'};
export function MetaboliteWorkbench(){
 const {datasets}=useDataSession();const [data,setData]=useState<Molecule|null>(null);const [tab,setTab]=useState('2d');const [group,setGroup]=useState(-1);const [selected,setSelected]=useState('');const [frame,setFrame]=useState(0);const [play,setPlay]=useState(false);const [error,setError]=useState('');const [start,setStart]=useState(1);const [end,setEnd]=useState(5000);
 function choose(d:Molecule){setData(d);setGroup(-1);setSelected('');setFrame(0);setPlay(false);setError('');setStart(1);setEnd(d.atoms.length||1);}
 useEffect(()=>{if(!play||tab!=='4d'||!data?.frames.length)return;const id=setInterval(()=>setFrame(f=>(f+1)%data.frames.length),450);return()=>clearInterval(id);},[data,play,tab]);
 const valid=Number.isInteger(start)&&Number.isInteger(end)&&start>=1&&end>=start&&end<=(data?.atoms.length||1);
 const groupIds=data&&group>=0?new Set(data.groups[group]?.atom_ids):null;
 const visible=(data?.atoms||[]).filter((a,i)=>valid&&i+1>=start&&i+1<=end&&(!groupIds||groupIds.has(a.id)));const ids=new Set(visible.map(a=>a.id));
 const model=useMemo(()=>data?moleculeScene(data):null,[data]);
 const animated=model?.atoms.map((a,i)=>({...a,...(tab==='4d'&&data?.frames[frame]?{x:data.frames[frame].positions[i][0],y:data.frames[frame].positions[i][1],z:data.frames[frame].positions[i][2]}:{})})).filter(a=>ids.has(a.id))||[];
 const scene=data?.has3d&&model&&animated.length?<ProteinAtomScene key={data.id} atoms={animated} data={model} moleculeName={data.name} onResidue={()=>{}}/>:<div className="data-empty"><h3>No 3D coordinates for this selection</h3><p>A molecular formula, feature name or abundance table does not determine a 3D structure. Upload explicit atoms, bonds and coordinates, or select a teaching example.</p></div>;
 const xMin=Math.min(0,...visible.map(a=>a.x2)),xMax=Math.max(1,...visible.map(a=>a.x2)),yMin=Math.min(0,...visible.map(a=>a.y2)),yMax=Math.max(1,...visible.map(a=>a.y2));const scale=Math.min(650/(xMax-xMin+1),330/(yMax-yMin+1));const points=new Map(visible.map(a=>[a.id,{x:70+(a.x2-xMin)*scale,y:60+(a.y2-yMin)*scale}]));
 const atom=data?.atoms.find(a=>a.id===selected);const imports=datasets.filter(d=>d.category==='metabolome'&&d.status==='ready'&&d.molecule);
 async function upload(file?:File){if(!file)return;try{if(file.size>5*1024*1024)throw Error('Choose a JSON bundle below 5 MiB.');choose(validateMolecule(JSON.parse(await file.text())));}catch(e){setError(e instanceof Error?e.message:'Cannot read molecule');}}
 function download(){if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=data.id.replace(/[^a-z0-9_-]/gi,'_')+'.json';a.click();URL.revokeObjectURL(url);}
 return <section className="protein-workbench metabolite-workbench"><header className="data-section-title"><div><h2>Metabolite, lipid & glycan structures</h2><p>Explore chemical connectivity, atom coordinates and supplied motion frames.</p></div><Button onClick={()=>choose(metaboliteSamples()[0])}>Load molecule example</Button></header>
 <div className="protein-controls"><label>Teaching molecule<select defaultValue="" onChange={e=>choose(metaboliteSamples()[+e.target.value])}><option value="" disabled>Choose a structure</option>{metaboliteSamples().map((m,i)=><option key={m.id} value={i}>{m.name} · {m.category}</option>)}</select></label><label>Upload molecule JSON<input type="file" accept=".json" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><Link href="/explore/loader">Data loader & samples →</Link>{data&&<Button variant="outline" onClick={download}>Export molecule</Button>}</div>
 {imports.length>0&&<label>Loaded structure<select defaultValue="" onChange={e=>{const d=imports.find(d=>d.id===e.target.value);if(d?.molecule)choose(d.molecule);}}><option value="" disabled>Choose imported molecule</option>{imports.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}{error&&<p role="alert" className="data-notice">{error}</p>}
 {!data?<div className="data-empty"><h3>Choose a molecule to begin</h3><p>Examples include ethanol, glycerol, palmitic acid, glucose-ring connectivity and maltose connectivity. Geometry and motion are synthetic; stereochemistry is omitted.</p></div>:<><div className="protein-evidence"><h3>{data.name} · {data.formula}</h3><p>{data.category} · {data.atoms.length} explicit atoms · {data.bonds.length} bonds · {data.frames.length} frames</p><p>{data.provenance}</p><p>Formula is supplied metadata; implicit hydrogens may be absent from the atom graph.</p></div>
 <div className="protein-controls"><label>Functional group<select value={group} onChange={e=>setGroup(+e.target.value)}><option value="-1">Whole molecule</option>{data.groups.map((g,i)=><option key={i} value={i}>{g.name}</option>)}</select></label><label>First atom in file<input type="number" min="1" max={data.atoms.length||1} value={start} onChange={e=>setStart(+e.target.value)}/></label><label>Last atom in file<input type="number" min="1" max={data.atoms.length||1} value={end} onChange={e=>setEnd(+e.target.value)}/></label><Button variant="outline" onClick={()=>{setGroup(-1);setStart(1);setEnd(data.atoms.length||1);}}>Show all atoms</Button><span>{visible.length} atoms displayed</span></div><p>Atom ranges refer to file order, not DNA or protein sequence positions. Group filters show supplied members; hidden bonds do not imply chemical cleavage.</p>{!valid&&<p role="alert">Choose an inclusive atom range within the file.</p>}
 <Tabs value={tab} onValueChange={v=>{setTab(v);setPlay(false);}}><TabsList><TabsTrigger value="2d">2D chemistry</TabsTrigger><TabsTrigger value="3d">3D atoms</TabsTrigger><TabsTrigger value="4d">4D motion</TabsTrigger><TabsTrigger value="evidence">Groups & evidence</TabsTrigger></TabsList>
 <TabsContent value="2d">{visible.length?<><svg className="metabolite-chemical" viewBox="0 0 800 460" role="img" aria-label={`2D chemical connectivity for ${data.name}`}>{data.bonds.filter(b=>ids.has(b.a)&&ids.has(b.b)).map((b,i)=>{const a=points.get(b.a)!,c=points.get(b.b)!;return <g key={i}>{Array.from({length:b.order},(_,j)=><line key={j} x1={a.x+(j-(b.order-1)/2)*5} y1={a.y} x2={c.x+(j-(b.order-1)/2)*5} y2={c.y} stroke="#99b9cd" strokeWidth="2"/>)}</g>;})}{visible.map(a=>{const p=points.get(a.id)!;return <g key={a.id} role="button" tabIndex={0} aria-label={`Select atom ${a.id}`} onClick={()=>setSelected(a.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(a.id);}}}><circle cx={p.x} cy={p.y} r={selected===a.id?19:15} fill="#0b2030" stroke={group>=0?'#2dd4bf':COLORS[a.element]||'#c084fc'} strokeWidth="2"/><text x={p.x} y={p.y+5} textAnchor="middle" fill={COLORS[a.element]||'#c084fc'} fontSize="16">{a.element}{a.charge?`${a.charge>0?'+':''}${a.charge}`:''}</text><text x={p.x} y={p.y+35} textAnchor="middle" fill="#d0e6f2" fontSize="12">{a.id}</text></g>;})}</svg><p>Explicit bonds and supplied 2D layout. Double/triple lines show bond order. No stereochemistry or hydrogen atoms are inferred. Green outlines indicate the selected functional group.</p>{atom&&<div className="protein-detail"><h3>{atom.id} · {atom.element}</h3><p>Formal charge: {atom.charge===undefined?'not supplied':atom.charge}</p><p>Groups: {data.groups.filter(g=>g.atom_ids.includes(atom.id)).map(g=>g.name).join(', ')||'none supplied'}</p><p>Bonds: {data.bonds.filter(b=>b.a===atom.id||b.b===atom.id).map(b=>`${b.a===atom.id?b.b:b.a} (order ${b.order})`).join(', ')||'none supplied'}</p></div>}</>:<div className="data-empty"><h3>No atom graph in this selection</h3><p>Provide atom identities, 2D layout coordinates and explicit bonds. A glycan composition alone does not specify its linkages.</p></div>}</TabsContent>
 <TabsContent value="3d">{scene}</TabsContent><TabsContent value="4d">{data.has3d&&data.frames.length>1?<><div className="protein-controls"><Button onClick={()=>setPlay(!play)}>{play?'Pause':'Play'}</Button><label>Frame {frame+1} / {data.frames.length}<input type="range" min="0" max={data.frames.length-1} value={frame} onChange={e=>{setFrame(+e.target.value);setPlay(false);}}/></label><strong>{data.frames[frame].time} {data.timeUnit}</strong></div>{scene}<p>Playback follows the supplied coordinates with fixed bond topology. It does not simulate reactions, binding or molecular dynamics.</p></>:<div className="data-empty"><h3>No coordinate trajectory</h3><p>Supply at least two complete coordinate frames with increasing time values and time units. Abundance time series cannot supply molecular motion.</p></div>}</TabsContent>
 <TabsContent value="evidence"><h3>Functional groups</h3>{data.groups.length?data.groups.map((g,i)=><div className="protein-detail" key={i}><h4>{g.name}</h4><p>{g.atom_ids.join(', ')}</p><Button variant="outline" onClick={()=>{setGroup(i);setTab('2d');}}>Inspect group</Button></div>):<p>No functional-group annotations supplied.</p>}<h3>Interaction annotations</h3>{data.interactions.length?data.interactions.map((i,j)=><p key={j}>{i.a} ↔ {i.b} · {i.type} · {i.evidence}</p>):<p>No interaction evidence supplied. Contacts are not inferred from atom proximity.</p>}<p>Connectivity teaching references: <a href="https://www.ebi.ac.uk/chebi/CHEBI:17234" target="_blank" rel="noreferrer">glucose</a>, <a href="https://www.ebi.ac.uk/chebi/CHEBI:17306" target="_blank" rel="noreferrer">maltose</a>. Teaching layouts omit anomeric and other stereochemistry.</p></TabsContent></Tabs>
 </>}
 <details><summary>Supported molecular structures and upload format</summary><p>The JSON format accepts metabolite, lipid, glycan and other small-molecule atom graphs with explicit bonds, optional groups and interactions, a 2D layout, and optional 3D trajectories. Download an example through the data loader. Maximum 5 MiB, 5,000 atoms and 100 frames. Supported elements: C, H, N, O, S, P, Se, F, Cl, Br, I, Zn, Fe, Mg and Ca. Supply aromatic bonds in an explicit Kekulé representation.</p><p>Raw SDF/MOL/PDB, SMILES interpretation, mass-spectrometry structure identification and conformer prediction are not implemented. Export an explicit JSON structure; no structure is guessed from a molecular formula, mass, lipid shorthand or glycan composition.</p></details>
 </section>;
}
