"use client";
import {useState} from 'react';
import {AMINO,type Structure} from '@/lib/protein-structure';
import {modificationColor,modificationGraph,type Modification} from '@/lib/protein-modifications';
export function ModificationChemistry({data,modification:m}:{data:Structure;modification:Modification}){
 const [selected,setSelected]=useState('');const graph=modificationGraph(data,m);const color=modificationColor(m);
 const nodes=graph.atoms.map((a,i)=>({...a,x2:300+Math.cos((i/Math.max(1,graph.atoms.length))*Math.PI*2)*175,y2:180+Math.sin((i/Math.max(1,graph.atoms.length))*Math.PI*2)*100}));const map=new Map(nodes.map(a=>[a.id,a]));
 const known=m.name.toLowerCase();const formula=known==='phosphorylation'?'Ser–CH₂–O–P(=O)(OH)₂':known==='acetylation'?'Lys–(CH₂)₄–NH–C(=O)–CH₃':null;
 return <section className="modification-chemistry" style={{borderColor:color}}><header><h3>2D chemical panel · {m.name}</h3><strong style={{color}}>{AMINO[data.sequence[m.residue-1]][0]} {m.residue}</strong></header><p>{m.evidence}</p>{graph.atoms.length>0?<><svg viewBox="0 0 600 370" role="img" aria-label={`Chemical connectivity of ${m.name} at residue ${m.residue}`}>
 {graph.bonds.map((b,i)=>{const a=map.get(b.a)!,c=map.get(b.b)!;const attachment=b.a===m.attachment_atom_id||b.b===m.attachment_atom_id;return <g key={i}>{Array.from({length:b.order},(_,j)=><line key={j} x1={a.x2+(j-(b.order-1)/2)*5} y1={a.y2} x2={c.x2+(j-(b.order-1)/2)*5} y2={c.y2} stroke={attachment?'#7dd3fc':color} strokeWidth={attachment?4:2}/>)}<title>{b.a} – {b.b}, order {b.order}{attachment?', attachment bond':''}</title></g>;})}
 {nodes.map(a=><g key={a.id} role="button" tabIndex={0} aria-label={`Inspect ${a.id}`} onClick={()=>setSelected(a.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(a.id);}}}><circle cx={a.x2} cy={a.y2} r="24" fill="#0b2030" stroke={graph.component.has(a.id)?color:'#7dd3fc'} strokeWidth={selected===a.id?5:3}/><text x={a.x2} y={a.y2+6} textAnchor="middle" fill="white" fontSize="19">{a.element}</text><text x={a.x2} y={a.y2+44} textAnchor="middle" fill={graph.component.has(a.id)?color:'#7dd3fc'} fontSize="14">{a.id}</text></g>)}
 </svg><p><strong style={{color}}>Colored atoms: modification component.</strong> Blue atom and bond: attachment to the original residue. Layout shows explicit connectivity, not bond angles. Bonds to the rest of the protein are outside this local panel.</p>{selected&&map.has(selected)&&<p role="status">Selected {selected} · {graph.component.has(selected)?'modification atom':'residue attachment atom'} · {graph.bonds.filter(b=>b.a===selected||b.b===selected).map(b=>`${b.a===selected?b.b:b.a} (bond order ${b.order})`).join(', ')}</p>}</>:<div className="data-empty"><h4>Site annotated; modification atoms are not mapped</h4><p>The sequence and structure show a site marker only. Add atom_ids and an attachment_atom_id with explicit bonds to display the chemical component.</p></div>}
 {formula&&<div className="modification-formula"><strong>Reference side-chain notation</strong><p>{formula}</p><small>Reference example only: {known==='phosphorylation'?'O-phosphoserine':'Nε-acetyllysine'}. It does not establish the chemistry of an arbitrary uploaded annotation. Hydrogens are implicit; charge and stereochemistry are not displayed.</small><p><a href={known==='phosphorylation'?'https://www.ebi.ac.uk/chebi/CHEBI:15811':'https://www.ebi.ac.uk/chebi/CHEBI:17752'} target="_blank" rel="noreferrer">ChEBI chemical reference</a></p></div>}
 </section>;
}
