"use client";
import {useEffect,useMemo,useState,useRef} from 'react';
import Link from 'next/link';
import {ModificationChemistry} from './modification-chemistry';
import {modifiedProteinSample,modificationColor} from '@/lib/protein-modifications';
import {ProteinAtomScene} from './protein-atom-scene';
import {Button} from './ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './ui/tabs';
import {useDataSession} from './data-session';
import {AMINO,MODIFICATIONS,proteinSample,proteinTeachingSamples,residueBoxSize,validateStructure,type Structure} from '@/lib/protein-structure';
const colors:Record<string,string>={C:'#91a9bc',N:'#60a5fa',O:'#fb7185',S:'#facc15',H:'#fff',P:'#fb923c'};
const classes:Record<string,string>={nonpolar:'#7896b6',polar:'#34d399',acidic:'#fb7185',basic:'#60a5fa',aromatic:'#c084fc'};
export function ProteinWorkbench(){
 const {datasets}=useDataSession();const [data,setData]=useState<Structure|null>(null);const [start,setStart]=useState(1);const [end,setEnd]=useState(20);const [focus,setFocus]=useState(1);const [error,setError]=useState('');const [angle,setAngle]=useState(30);const [tilt,setTilt]=useState(20);const [zoom,setZoom]=useState(1);const [frame,setFrame]=useState(0);const [play,setPlay]=useState(false);const [tab,setTab]=useState('2d');const [interaction,setInteraction]=useState('All');const [labels,setLabels]=useState(false);
 const [minBox,setMinBox]=useState(28);const [maxBox,setMaxBox]=useState(64);const [boxMode,setBoxMode]=useState('auto');const [wrap,setWrap]=useState(true);const strip=useRef<HTMLDivElement>(null);const [stripWidth,setStripWidth]=useState(900);
 useEffect(()=>{const el=strip.current;if(!el)return;const observer=new ResizeObserver(entries=>setStripWidth(entries[0].contentRect.width));observer.observe(el);return()=>observer.disconnect();},[data]);
 const [modIndex,setModIndex]=useState(0);
 const choose=(d:Structure)=>{setModIndex(0);setData(d);setStart(1);setEnd(Math.min(20,d.sequence.length));setFocus(1);setFrame(0);setPlay(false);setError('');};
 useEffect(()=>{if(!play||tab!=='4d'||!data?.frames.length)return;const id=setInterval(()=>setFrame(f=>(f+1)%data.frames.length),450);return()=>clearInterval(id);},[play,tab,data]);
 const valid=!!data&&Number.isInteger(start)&&Number.isInteger(end)&&start>=1&&end>=start&&end<=data.sequence.length&&end-start<500;
 const sequence=valid?data!.sequence.slice(start-1,end):'';
 const atoms=useMemo(()=>{if(!data||!valid)return [];return data.atoms.map((a,i)=>({...a,...(tab==='4d'&&data.frames[frame]?Object.fromEntries(['x','y','z'].map((k,j)=>[k,data.frames[frame].positions[i][j]])):{})})).filter(a=>a.residue>=start&&a.residue<=end);},[data,valid,start,end,frame,tab]);
 const point=new Map(atoms.map(a=>[a.id,a]));const edges=data?.interactions.filter(i=>point.has(i.a)&&point.has(i.b)&&(interaction==='All'||i.type===interaction))||[];const mods=data?.modifications.filter(m=>m.residue>=start&&m.residue<=end)||[];
 const activeMod=mods.includes(data?.modifications[modIndex]!)?data!.modifications[modIndex]:mods[0];
 const selectedResidue=Math.max(start,Math.min(end,focus));const aa=data?.sequence[selectedResidue-1]||'A';const info=AMINO[aa];
 async function upload(file?:File){if(!file)return;try{if(file.size>5*1024*1024)throw Error('Choose a JSON bundle smaller than 5 MiB.');choose(validateStructure(JSON.parse(await file.text())));}catch(e){setError(e instanceof Error?e.message:'Cannot read structure file');}}
 function download(){if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='protein-structure.json';a.click();URL.revokeObjectURL(url);}
 const imported=datasets.filter(d=>d.category==='proteome'&&d.status==='ready'&&d.headers.includes('sequence'));
 const scene=data&&atoms.length?<ProteinAtomScene atoms={atoms} data={data} onResidue={setFocus} modification={activeMod}/>:<div className="data-empty"><h3>No atomic coordinates in this range</h3><p>Upload mapped atoms and bonds. A sequence alone does not supply a structural model.</p></div>;
 const boxWidth=residueBoxSize(sequence.length,stripWidth,minBox,maxBox,boxMode);
 return <section className="protein-workbench"><div className="data-section-title"><div><h2>Peptide & atomic structure explorer</h2><p>Choose a sequence interval, inspect its chemistry, then explore coordinates and motion.</p></div><div className="protein-controls"><Button onClick={()=>choose(modifiedProteinSample())}>Load modified peptide</Button><Button variant="outline" onClick={()=>choose(proteinSample())}>Load 1–20 example</Button></div></div>
 <div className="protein-controls"><label>Teaching dataset<select defaultValue="" onChange={e=>{const d=[...proteinTeachingSamples(),modifiedProteinSample()][+e.target.value];if(d)choose(d);}}><option value="" disabled>Choose an example</option>{["21 residues · backbone & motion","100 residues · all amino acids & modifications","20 residues · sequence only / missing structure","21 residues · phosphate & acetyl chemical groups"].map((label,i)=><option key={label} value={i}>{label}</option>)}</select></label><label className="protein-upload">Upload structure JSON<input type="file" accept=".json" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><Link href="/explore/loader">Upload protein FASTA →</Link><a href="/data/protein_structure.json" download>Download example bundle</a>{data&&<Button variant="outline" onClick={download}>Export current bundle</Button>}</div>
 {imported.length>0&&<label>Use loaded sequence<select defaultValue="" onChange={e=>{const [di,ri]=e.target.value.split(':').map(Number),d=imported[di];if(!d)return;const row=d.rows[ri],sequence=row[d.headers.indexOf('sequence')];try{if(d.structure){choose(d.structure);return;}choose(validateStructure({reference:row[0],sequence,provenance:`${d.source}: ${d.name}; sequence only`,unit:'angstrom',atoms:[],bonds:[],interactions:[],modifications:[],frames:[],timeUnit:''}));}catch(e){setError(String(e));}}}><option value="" disabled>Select a protein</option>{imported.flatMap((d,di)=>d.rows.map((r,ri)=><option key={`${di}:${ri}`} value={`${di}:${ri}`}>{d.name} · {r[0]}</option>))}</select></label>}
 {error&&<p role="alert" className="data-notice">{error}</p>}
 {!data?<div className="data-empty"><h3>Explore a full amino-acid segment</h3><p>Load the synthetic example or your own coordinates. Your existing protein tables and spectra remain below.</p></div>:<><div className="protein-evidence"><strong>{data.reference} · {data.sequence.length} residues</strong><p>{data.provenance}</p><span>Coordinates: {data.unit} · {data.atoms.length} atoms · {data.frames.length} frames</span></div>
 <div className="protein-controls"><label>Start (inclusive)<input type="number" min="1" max={data.sequence.length} value={start} onChange={e=>{setStart(+e.target.value);setPlay(false);}}/></label><label>End (inclusive)<input type="number" min={start} max={data.sequence.length} value={end} onChange={e=>{setEnd(+e.target.value);setPlay(false);}}/></label><Button variant="outline" onClick={()=>{setStart(1);setEnd(Math.min(20,data.sequence.length));}}>1–20</Button><Button variant="outline" onClick={()=>{setStart(1);setEnd(data.sequence.length);}}>Full sequence</Button><Button variant="outline" onClick={()=>{const width=end-start;const next=Math.min(data.sequence.length-width,start+width+1);setStart(next);setEnd(next+width);}} disabled={!valid||end===data.sequence.length}>Next window</Button><span>{valid?`${sequence.length} residues selected`:'Select 1–500 residues within the sequence.'}</span></div>
 <div className="protein-controls"><label>Start position<input type="range" min="1" max={data.sequence.length} value={Math.max(1,start)} onChange={e=>{const n=+e.target.value;setStart(n);if(end<n)setEnd(n);}}/></label><label>End position<input type="range" min="1" max={data.sequence.length} value={Math.max(1,end)} onChange={e=>{const n=+e.target.value;setEnd(n);if(start>n)setStart(n);}}/></label></div>
 {valid&&<><div className="protein-controls"><label>Residue box display<select value={boxMode} onChange={e=>setBoxMode(e.target.value)}><option value="auto">Automatic fit</option><option value="min">Minimum size</option><option value="max">Maximum size</option></select></label><label>Minimum width: {minBox}px<input type="range" min="28" max="60" value={minBox} onChange={e=>{const n=+e.target.value;setMinBox(n);if(maxBox<n)setMaxBox(n);}}/></label><label>Maximum width: {maxBox}px<input type="range" min={minBox} max="96" value={maxBox} onChange={e=>setMaxBox(+e.target.value)}/></label><label><input type="checkbox" checked={wrap} onChange={e=>setWrap(e.target.checked)}/> Wrap boxes into rows</label><span>{boxWidth}px per residue</span></div><div ref={strip} className="protein-strip" style={{flexWrap:wrap?'wrap':'nowrap'}} aria-label="Selected amino acids">{[...sequence].map((s,i)=><button key={i} aria-pressed={selectedResidue===start+i} onClick={()=>{setFocus(start+i);const mi=data.modifications.findIndex(m=>m.residue===start+i);if(mi>=0)setModIndex(mi);}} title={`${AMINO[s][0]} ${start+i}`} style={{borderColor:classes[AMINO[s][2]],minWidth:boxWidth,width:boxWidth,flexShrink:0}}><span>{start+i}</span><b>{s}</b>{mods.some(m=>m.residue===start+i)&&<em aria-label="Modified residue" style={{color:modificationColor(mods.find(m=>m.residue===start+i)!)}}>◆</em>}</button>)}</div>
 {activeMod&&<section className="modification-selection" style={{borderColor:modificationColor(activeMod)}}><label>Highlighted modification<select value={data.modifications.indexOf(activeMod)} onChange={e=>{setModIndex(+e.target.value);setFocus(data.modifications[+e.target.value].residue);}}>{mods.map(m=><option key={data.modifications.indexOf(m)} value={data.modifications.indexOf(m)}>{data.sequence[m.residue-1]}{m.residue} · {m.name} · {m.atom_ids?.length?`${m.atom_ids.length} mapped component atoms`:'site annotation only'}</option>)}</select></label><p><strong style={{color:modificationColor(activeMod)}}>◆ {activeMod.name} at {data.sequence[activeMod.residue-1]}{activeMod.residue}</strong> · Same marker across 2D, 3D and 4D. {activeMod.atom_ids?.length?'Modification atoms are mapped explicitly.':'Only the residue is marked; no modified atoms are inferred.'}</p></section>}
 <Tabs value={tab} onValueChange={v=>{setTab(v);setPlay(false);}}><TabsList><TabsTrigger value="2d">2D chemistry</TabsTrigger><TabsTrigger value="3d">3D atoms</TabsTrigger><TabsTrigger value="4d">4D motion</TabsTrigger><TabsTrigger value="mods">Modifications</TabsTrigger><TabsTrigger value="contacts">Interactions</TabsTrigger></TabsList>
 <TabsContent value="2d">{activeMod&&<ModificationChemistry data={data} modification={activeMod}/>}<div className="protein-scroll"><svg width={Math.max(900,sequence.length*150)} height="215" role="img" aria-label="Connected peptide backbone with side-chain groups">{[...sequence].map((s,i)=>{const x=35+i*150;const siteMod=mods.find(m=>m.residue===start+i);return <g key={i}>{siteMod&&<><rect x={x-20} y="8" width="140" height="190" rx="12" fill="none" stroke={modificationColor(siteMod)} strokeWidth="3"/><text x={x+45} y="190" textAnchor="middle" fill={modificationColor(siteMod)} fontSize="12">◆ {siteMod.name.slice(0,17)}</text></>}<text x={x+35} y="28" fill={classes[AMINO[s][2]]}>{s}{start+i}</text><line x1={x} y1="100" x2={x+50} y2="100" stroke="currentColor"/><line x1={x+50} y1="100" x2={x+100} y2="100" stroke="currentColor"/>{i<sequence.length-1&&<line x1={x+100} y1="100" x2={x+150} y2="100" stroke="#38bdf8" strokeWidth="3"/>}<line x1={x+97} y1="92" x2={x+97} y2="63" stroke="currentColor"/><line x1={x+103} y1="92" x2={x+103} y2="63" stroke="currentColor"/><line x1={x+50} y1="108" x2={x+50} y2="145" stroke="currentColor"/>{[['N',x,100],['Cα',x+50,100],['C',x+100,100],['O',x+100,55],['R',x+50,158]].map(([t,tx,ty])=><text key={t} x={tx} y={Number(ty)+5} textAnchor="middle" fill="currentColor" stroke="var(--background)" paintOrder="stroke" strokeWidth="5">{t}</text>)}</g>;})}</svg></div><p>Backbone connectivity schematic. Blue links are peptide C–N bonds. R denotes the selected side chain; proline closes its side chain to N. Hydrogen atoms, stereochemistry, terminal groups and modification atoms are omitted. Range edges are display cuts, not chemical cleavage.</p><div className="protein-detail"><h3>{selectedResidue} · {info[0]} ({aa})</h3><p className="protein-formula">R = {info[1]}</p><p>{info[2]} side-chain class. Condensed neutral-form notation; protonation depends on pH and environment.</p><p>{mods.filter(m=>m.residue===selectedResidue).map(m=>m.name+': '+m.evidence).join(' · ')||'No modification annotation supplied at this residue.'}</p></div></TabsContent>
 <TabsContent value="3d">{scene}</TabsContent>
 <TabsContent value="4d">{data.frames.length>1?<><div className="protein-controls"><Button onClick={()=>setPlay(!play)}>{play?'Pause':'Play'}</Button><label>Frame {frame+1} / {data.frames.length}<input type="range" min="0" max={data.frames.length-1} value={frame} onChange={e=>{setFrame(+e.target.value);setPlay(false);}}/></label><strong>{data.frames[frame]?.time} {data.timeUnit}</strong></div>{scene}<p>Frames use the bundle’s atom order and fixed bond topology. Only supplied coordinates move; this viewer does not run dynamics or simulate chemical reactions.</p></>:<div className="data-empty"><h3>No coordinate trajectory</h3><p>Provide at least two complete coordinate frames with increasing times and time units. A static fold or abundance time course cannot supply molecular motion.</p></div>}</TabsContent>
 <TabsContent value="mods">{activeMod&&<><ModificationChemistry data={data} modification={activeMod}/><div className="protein-controls"><Button onClick={()=>setTab('3d')}>View highlighted atoms in 3D</Button><Button onClick={()=>setTab('4d')}>Follow modification in 4D</Button></div></>}<h3>{mods.length} annotated sites in this range</h3>{mods.length?mods.map((m,i)=><div className="protein-detail" key={i}><strong>{data.sequence[m.residue-1]}{m.residue} · {m.name}</strong><p>{m.evidence}</p></div>):<p>No modification evidence supplied. This does not establish that the protein is unmodified.</p>}<h3>Modification reference</h3><p>Common examples, not an exhaustive list or predictions. Custom modification names and evidence are accepted in uploaded bundles. Annotation labels do not add modified atoms to the structure.</p><div className="protein-mod-grid">{MODIFICATIONS.map(([name,sites,note])=><article key={name}><h4>{name}</h4><p>Typical sites: {sites}</p><p>{note}</p></article>)}</div><p>Reference: <a href="https://www.unimod.org/" target="_blank" rel="noreferrer">Unimod modification database</a>.</p></TabsContent>
 <TabsContent value="contacts"><label>Interaction type<select value={interaction} onChange={e=>setInteraction(e.target.value)}><option>All</option>{[...new Set(data.interactions.map(i=>i.type))].map(t=><option key={t}>{t}</option>)}</select></label>{scene}<div className="protein-scroll"><table><thead><tr><th>Atoms</th><th>Interaction</th><th>Distance ({data.unit})</th><th>Evidence</th></tr></thead><tbody>{edges.map((i,j)=>{const a=point.get(i.a)!,b=point.get(i.b)!;return <tr key={j}><td>{i.a} ↔ {i.b}</td><td>{i.type}</td><td>{Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z).toFixed(2)}</td><td>{i.evidence}</td></tr>;})}</tbody></table></div>{!edges.length&&<p>No interaction annotations with both endpoints inside this range.</p>}<p>Supported annotation types include hydrogen bonds, salt bridges, disulfides, hydrophobic contacts, π–π and cation–π contacts, metal coordination, and ligand contacts. Any custom type is accepted. Distances alone do not establish these interactions; atom typing, geometry, protonation and experimental context matter.</p></TabsContent>
 </Tabs></>}
 </>}
 <details><summary>Prepare your own chemical structure bundle</summary><p>Download the example JSON as a schema template. Supply a standard-amino-acid sequence and a reference ID, map every atom to a 1-based sequence residue, and include explicit bonds and provenance. PDB author residue numbers and insertion codes must first be mapped to these sequence positions. Up to 500 sequence residues, 5,000 atoms and 100 frames are supported; select at most 500 residues at a time.</p><p>Use angstrom for physical coordinates. Frames contain xyz triplets in the exact atoms-array order. Unknown modifications and interactions are preserved as annotations with evidence. Include their actual atoms and bonds to render their chemical geometry. Direct PDB/mmCIF parsing, folding, energy calculations, full glycan topology reconstruction and chemical reaction simulation are not implemented.</p></details>
 </section>;
}
