"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Button} from './ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './ui/tabs';
import {useDataSession} from './data-session';
import {AMINO,MODIFICATIONS,proteinSample,validateStructure,type Structure} from '@/lib/protein-structure';
const colors:Record<string,string>={C:'#91a9bc',N:'#60a5fa',O:'#fb7185',S:'#facc15',H:'#fff',P:'#fb923c'};
const classes:Record<string,string>={nonpolar:'#7896b6',polar:'#34d399',acidic:'#fb7185',basic:'#60a5fa',aromatic:'#c084fc'};
export function ProteinWorkbench(){
 const {datasets}=useDataSession();const [data,setData]=useState<Structure|null>(null);const [start,setStart]=useState(1);const [end,setEnd]=useState(20);const [focus,setFocus]=useState(1);const [error,setError]=useState('');const [angle,setAngle]=useState(30);const [tilt,setTilt]=useState(20);const [zoom,setZoom]=useState(1);const [frame,setFrame]=useState(0);const [play,setPlay]=useState(false);const [tab,setTab]=useState('2d');const [interaction,setInteraction]=useState('All');const [labels,setLabels]=useState(false);
 const choose=(d:Structure)=>{setData(d);setStart(1);setEnd(Math.min(20,d.sequence.length));setFocus(1);setFrame(0);setPlay(false);setError('');};
 useEffect(()=>{if(!play||tab!=='4d'||!data?.frames.length)return;const id=setInterval(()=>setFrame(f=>(f+1)%data.frames.length),450);return()=>clearInterval(id);},[play,tab,data]);
 const valid=!!data&&Number.isInteger(start)&&Number.isInteger(end)&&start>=1&&end>=start&&end<=data.sequence.length&&end-start<100;
 const sequence=valid?data!.sequence.slice(start-1,end):'';
 const atoms=useMemo(()=>{if(!data||!valid)return [];return data.atoms.map((a,i)=>({...a,...(tab==='4d'&&data.frames[frame]?Object.fromEntries(['x','y','z'].map((k,j)=>[k,data.frames[frame].positions[i][j]])):{})})).filter(a=>a.residue>=start&&a.residue<=end);},[data,valid,start,end,frame,tab]);
 const projected=useMemo(()=>{if(!atoms.length)return [];const center=['x','y','z'].map(k=>atoms.reduce((s,a)=>s+a[k as 'x'|'y'|'z'],0)/atoms.length);const radius=Math.max(1,...atoms.map(a=>Math.hypot(a.x-center[0],a.y-center[1],a.z-center[2])));const u=angle*Math.PI/180,v=tilt*Math.PI/180;return atoms.map(a=>{const x=a.x-center[0],y=a.y-center[1],z=a.z-center[2];const xx=x*Math.cos(u)+z*Math.sin(u),zz=-x*Math.sin(u)+z*Math.cos(u);return {...a,px:450+xx/radius*180*zoom,py:230+(y*Math.cos(v)-zz*Math.sin(v))/radius*180*zoom,depth:y*Math.sin(v)+zz*Math.cos(v)};});},[atoms,angle,tilt,zoom]);
 const point=new Map(projected.map(a=>[a.id,a]));const edges=data?.interactions.filter(i=>point.has(i.a)&&point.has(i.b)&&(interaction==='All'||i.type===interaction))||[];const mods=data?.modifications.filter(m=>m.residue>=start&&m.residue<=end)||[];
 const selectedResidue=Math.max(start,Math.min(end,focus));const aa=data?.sequence[selectedResidue-1]||'A';const info=AMINO[aa];
 async function upload(file?:File){if(!file)return;try{if(file.size>5*1024*1024)throw Error('Choose a JSON bundle smaller than 5 MiB.');choose(validateStructure(JSON.parse(await file.text())));}catch(e){setError(e instanceof Error?e.message:'Cannot read structure file');}}
 function download(){if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='protein-structure.json';a.click();URL.revokeObjectURL(url);}
 const imported=datasets.filter(d=>d.category==='proteome'&&d.status==='ready'&&d.headers.includes('sequence'));
 const scene=<><div className="protein-controls"><label>Rotate<input aria-label="Rotate structure" type="range" min="-180" max="180" value={angle} onChange={e=>setAngle(+e.target.value)}/></label><label>Tilt<input aria-label="Tilt structure" type="range" min="-90" max="90" value={tilt} onChange={e=>setTilt(+e.target.value)}/></label><label>Zoom<input aria-label="Zoom structure" type="range" min=".5" max="2" step=".05" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/> Atom labels</label></div>{atoms.length?<svg className="protein-scene" viewBox="0 0 900 460" role="img" aria-label={`Protein atoms for residues ${start} to ${end}`}>
 {data?.bonds.map((b,i)=>{const a=point.get(b.a),c=point.get(b.b);return a&&c?<g key={i}><line x1={a.px} y1={a.py} x2={c.px} y2={c.py} stroke="#8b9bab" strokeWidth="2"/>{b.order>1&&<line x1={a.px+4} y1={a.py+4} x2={c.px+4} y2={c.py+4} stroke="#8b9bab" strokeWidth="1"/>}{b.order===3&&<line x1={a.px-4} y1={a.py-4} x2={c.px-4} y2={c.py-4} stroke="#8b9bab"/>}</g>:null;})}
 {edges.map((i,j)=>{const a=point.get(i.a)!,b=point.get(i.b)!;return <line key={j} x1={a.px} y1={a.py} x2={b.px} y2={b.py} stroke="#fbbf24" strokeWidth="2" strokeDasharray="5 5"><title>{i.type}: {i.evidence}</title></line>;})}
 {[...projected].sort((a,b)=>a.depth-b.depth).map(a=><g key={a.id} onClick={()=>setFocus(a.residue)}><circle cx={a.px} cy={a.py} r={a.residue===selectedResidue?6:4} fill={colors[a.element]||'#c084fc'} stroke={a.residue===selectedResidue?'white':'none'}><title>{a.id} · residue {a.residue} · {a.element}</title></circle>{labels&&<text x={a.px+7} y={a.py-7} fill="white" fontSize="12">{a.id}</text>}</g>)}
 </svg>:<div className="data-empty"><h3>No atomic coordinates in this range</h3><p>Upload a structure bundle with residue-mapped atoms and bonds. A sequence alone does not determine an experimentally supported fold.</p></div>}<p className="data-help">C gray · N blue · O pink · S yellow · P orange. Solid lines: supplied bonds. Dashed gold: annotated interactions. Only endpoints inside the range are shown. No contacts or bonds are inferred from distance.</p></>;
 return <section className="protein-workbench"><div className="data-section-title"><div><h2>Peptide & atomic structure explorer</h2><p>Choose a sequence interval, inspect its chemistry, then explore coordinates and motion.</p></div><Button onClick={()=>choose(proteinSample())}>Load 1–20 example</Button></div>
 <div className="protein-controls"><label className="protein-upload">Upload structure JSON<input type="file" accept=".json" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><Link href="/explore/loader">Upload protein FASTA →</Link><a href="/data/protein_structure.json" download>Download example bundle</a>{data&&<Button variant="outline" onClick={download}>Export current bundle</Button>}</div>
 {imported.length>0&&<label>Use loaded sequence<select defaultValue="" onChange={e=>{const [di,ri]=e.target.value.split(':').map(Number),d=imported[di];if(!d)return;const row=d.rows[ri],sequence=row[d.headers.indexOf('sequence')];try{if(d.structure){choose(d.structure);return;}choose(validateStructure({reference:row[0],sequence,provenance:`${d.source}: ${d.name}; sequence only`,unit:'angstrom',atoms:[],bonds:[],interactions:[],modifications:[],frames:[],timeUnit:''}));}catch(e){setError(String(e));}}}><option value="" disabled>Select a protein</option>{imported.flatMap((d,di)=>d.rows.map((r,ri)=><option key={`${di}:${ri}`} value={`${di}:${ri}`}>{d.name} · {r[0]}</option>))}</select></label>}
 {error&&<p role="alert" className="data-notice">{error}</p>}
 {!data?<div className="data-empty"><h3>Explore a full amino-acid segment</h3><p>Load the synthetic example or your own coordinates. Your existing protein tables and spectra remain below.</p></div>:<><div className="protein-evidence"><strong>{data.reference} · {data.sequence.length} residues</strong><p>{data.provenance}</p><span>Coordinates: {data.unit} · {data.atoms.length} atoms · {data.frames.length} frames</span></div>
 <div className="protein-controls"><label>Start (inclusive)<input type="number" min="1" max={data.sequence.length} value={start} onChange={e=>{setStart(+e.target.value);setPlay(false);}}/></label><label>End (inclusive)<input type="number" min={start} max={data.sequence.length} value={end} onChange={e=>{setEnd(+e.target.value);setPlay(false);}}/></label><Button variant="outline" onClick={()=>{setStart(1);setEnd(Math.min(20,data.sequence.length));}}>1–20</Button><span>{valid?`${sequence.length} residues selected`:'Select 1–100 residues within the sequence.'}</span></div>
 {valid&&<><div className="protein-strip" aria-label="Selected amino acids">{[...sequence].map((s,i)=><button key={i} aria-pressed={selectedResidue===start+i} onClick={()=>setFocus(start+i)} style={{borderColor:classes[AMINO[s][2]]}}><span>{start+i}</span><b>{s}</b>{mods.some(m=>m.residue===start+i)&&<em>●</em>}</button>)}</div>
 <Tabs value={tab} onValueChange={v=>{setTab(v);setPlay(false);}}><TabsList><TabsTrigger value="2d">2D chemistry</TabsTrigger><TabsTrigger value="3d">3D atoms</TabsTrigger><TabsTrigger value="4d">4D motion</TabsTrigger><TabsTrigger value="mods">Modifications</TabsTrigger><TabsTrigger value="contacts">Interactions</TabsTrigger></TabsList>
 <TabsContent value="2d"><div className="protein-scroll"><svg width={Math.max(900,sequence.length*150)} height="215" role="img" aria-label="Connected peptide backbone with side-chain groups">{[...sequence].map((s,i)=>{const x=35+i*150;return <g key={i}><text x={x+35} y="28" fill={classes[AMINO[s][2]]}>{s}{start+i}</text><line x1={x} y1="100" x2={x+50} y2="100" stroke="currentColor"/><line x1={x+50} y1="100" x2={x+100} y2="100" stroke="currentColor"/>{i<sequence.length-1&&<line x1={x+100} y1="100" x2={x+150} y2="100" stroke="#38bdf8" strokeWidth="3"/>}<line x1={x+97} y1="92" x2={x+97} y2="63" stroke="currentColor"/><line x1={x+103} y1="92" x2={x+103} y2="63" stroke="currentColor"/><line x1={x+50} y1="108" x2={x+50} y2="145" stroke="currentColor"/>{[['N',x,100],['Cα',x+50,100],['C',x+100,100],['O',x+100,55],['R',x+50,158]].map(([t,tx,ty])=><text key={t} x={tx} y={Number(ty)+5} textAnchor="middle" fill="currentColor" stroke="var(--background)" paintOrder="stroke" strokeWidth="5">{t}</text>)}</g>;})}</svg></div><p>Backbone connectivity schematic. Blue links are peptide C–N bonds. R denotes the selected side chain; proline closes its side chain to N. Hydrogen atoms, stereochemistry, terminal groups and modification atoms are omitted. Range edges are display cuts, not chemical cleavage.</p><div className="protein-detail"><h3>{selectedResidue} · {info[0]} ({aa})</h3><p className="protein-formula">R = {info[1]}</p><p>{info[2]} side-chain class. Condensed neutral-form notation; protonation depends on pH and environment.</p><p>{mods.filter(m=>m.residue===selectedResidue).map(m=>m.name+': '+m.evidence).join(' · ')||'No modification annotation supplied at this residue.'}</p></div></TabsContent>
 <TabsContent value="3d">{scene}</TabsContent>
 <TabsContent value="4d">{data.frames.length>1?<><div className="protein-controls"><Button onClick={()=>setPlay(!play)}>{play?'Pause':'Play'}</Button><label>Frame {frame+1} / {data.frames.length}<input type="range" min="0" max={data.frames.length-1} value={frame} onChange={e=>{setFrame(+e.target.value);setPlay(false);}}/></label><strong>{data.frames[frame]?.time} {data.timeUnit}</strong></div>{scene}<p>Frames use the bundle’s atom order and fixed bond topology. Only supplied coordinates move; this viewer does not run dynamics or simulate chemical reactions.</p></>:<div className="data-empty"><h3>No coordinate trajectory</h3><p>Provide at least two complete coordinate frames with increasing times and time units. A static fold or abundance time course cannot supply molecular motion.</p></div>}</TabsContent>
 <TabsContent value="mods"><h3>{mods.length} annotated sites in this range</h3>{mods.length?mods.map((m,i)=><div className="protein-detail" key={i}><strong>{data.sequence[m.residue-1]}{m.residue} · {m.name}</strong><p>{m.evidence}</p></div>):<p>No modification evidence supplied. This does not establish that the protein is unmodified.</p>}<h3>Modification reference</h3><p>Common examples, not an exhaustive list or predictions. Custom modification names and evidence are accepted in uploaded bundles. Annotation labels do not add modified atoms to the structure.</p><div className="protein-mod-grid">{MODIFICATIONS.map(([name,sites,note])=><article key={name}><h4>{name}</h4><p>Typical sites: {sites}</p><p>{note}</p></article>)}</div><p>Reference: <a href="https://www.unimod.org/" target="_blank" rel="noreferrer">Unimod modification database</a>.</p></TabsContent>
 <TabsContent value="contacts"><label>Interaction type<select value={interaction} onChange={e=>setInteraction(e.target.value)}><option>All</option>{[...new Set(data.interactions.map(i=>i.type))].map(t=><option key={t}>{t}</option>)}</select></label>{scene}<div className="protein-scroll"><table><thead><tr><th>Atoms</th><th>Interaction</th><th>Distance ({data.unit})</th><th>Evidence</th></tr></thead><tbody>{edges.map((i,j)=>{const a=point.get(i.a)!,b=point.get(i.b)!;return <tr key={j}><td>{i.a} ↔ {i.b}</td><td>{i.type}</td><td>{Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z).toFixed(2)}</td><td>{i.evidence}</td></tr>;})}</tbody></table></div>{!edges.length&&<p>No interaction annotations with both endpoints inside this range.</p>}<p>Supported annotation types include hydrogen bonds, salt bridges, disulfides, hydrophobic contacts, π–π and cation–π contacts, metal coordination, and ligand contacts. Any custom type is accepted. Distances alone do not establish these interactions; atom typing, geometry, protonation and experimental context matter.</p></TabsContent>
 </Tabs></>}
 </>}
 <details><summary>Prepare your own chemical structure bundle</summary><p>Download the example JSON as a schema template. Supply a standard-amino-acid sequence and a reference ID, map every atom to a 1-based sequence residue, and include explicit bonds and provenance. PDB author residue numbers and insertion codes must first be mapped to these sequence positions. Up to 500 sequence residues, 5,000 atoms and 100 frames are supported; select at most 100 residues at a time.</p><p>Use angstrom for physical coordinates. Frames contain xyz triplets in the exact atoms-array order. Unknown modifications and interactions are preserved as annotations with evidence. Include their actual atoms and bonds to render their chemical geometry. Direct PDB/mmCIF parsing, folding, energy calculations, full glycan topology reconstruction and chemical reaction simulation are not implemented.</p></details>
 </section>;
}
