"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Button} from './ui/button';
import {AMINO,type Atom,type Structure} from '@/lib/protein-structure';
import {modificationColor,type Modification} from '@/lib/protein-modifications';
const COLORS:Record<string,string>={C:'#96adc1',N:'#60a5fa',O:'#fb7185',S:'#facc15',H:'#f1f5f9',P:'#fb923c'};
export function ProteinAtomScene({atoms:allAtoms,data,onResidue,modification}:{atoms:Atom[];data:Structure;onResidue:(n:number)=>void;modification?:Modification}){
 const [selected,setSelected]=useState('');const [rotation,setRotation]=useState([.5,.3]);const [zoom,setZoom]=useState(1);const [pan,setPan]=useState([0,0]);const [centerAtom,setCenterAtom]=useState('');const [expanded,setExpanded]=useState(false);const [labels,setLabels]=useState(false);const [filter,setFilter]=useState('All');const [size,setSize]=useState(1);const svg=useRef<SVGSVGElement>(null);const gesture=useRef({points:new Map<number,{x:number;y:number}>(),moved:false,downAtom:'',lastAtom:'',lastClick:0});
 const [isolate,setIsolate]=useState(false);const [showModification,setShowModification]=useState(true);
 const component=new Set(modification?.atom_ids||[]);const modColor=modification?modificationColor(modification):'#2dd4bf';
 const atoms=isolate&&modification?allAtoms.filter(a=>a.residue===modification.residue||component.has(a.id)):allAtoms;
 const selectedAtom=atoms.find(a=>a.id===selected);const atomMap=new Map(atoms.map(a=>[a.id,a]));
 const reset=()=>{setZoom(1);setPan([0,0]);setCenterAtom('');};
 useEffect(()=>{reset();setSelected('');},[data.reference,atoms[0]?.id,atoms.at(-1)?.id]);
 useEffect(()=>{const el=svg.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();setZoom(z=>Math.min(12,Math.max(.25,z*Math.exp(-e.deltaY*.002))));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[atoms.length]);
 const points=useMemo(()=>{if(!atoms.length)return [];const target=atoms.find(a=>a.id===centerAtom);const center=target?[target.x,target.y,target.z]:['x','y','z'].map(k=>atoms.reduce((s,a)=>s+a[k as 'x'|'y'|'z'],0)/atoms.length);const extent=Math.max(1,...atoms.map(a=>Math.hypot(a.x-center[0],a.y-center[1],a.z-center[2])));const [u,v]=rotation;return atoms.map(a=>{const x=a.x-center[0],y=a.y-center[1],z=a.z-center[2];const xx=x*Math.cos(u)+z*Math.sin(u),zz=-x*Math.sin(u)+z*Math.cos(u);return {...a,px:450+pan[0]+xx/extent*180*zoom,py:230+pan[1]+(y*Math.cos(v)-zz*Math.sin(v))/extent*180*zoom,depth:y*Math.sin(v)+zz*Math.cos(v)};});},[atoms,centerAtom,rotation,pan,zoom]);
 const map=new Map(points.map(a=>[a.id,a]));const interactions=data.interactions.filter(i=>map.has(i.a)&&map.has(i.b)&&(filter==='All'||filter===i.type));
 const inspect=(a:Atom)=>{setSelected(a.id);onResidue(a.residue);};
 const focus=(a:Atom)=>{inspect(a);setCenterAtom(a.id);setPan([0,0]);setZoom(4);};
 const bonded=data.bonds.filter(b=>b.a===selected||b.b===selected);const nearby=selectedAtom?atoms.filter(a=>a.id!==selected).map(a=>({a,d:Math.hypot(a.x-selectedAtom.x,a.y-selectedAtom.y,a.z-selectedAtom.z)})).sort((a,b)=>a.d-b.d).slice(0,5):[];
 return <div className={`protein-atom-view ${expanded?'expanded':''}`}><div className="protein-controls"><Button variant="outline" onClick={()=>setZoom(z=>Math.min(12,z*1.3))}>Zoom +</Button><Button variant="outline" onClick={()=>setZoom(z=>Math.max(.25,z/1.3))}>Zoom −</Button><Button variant="outline" onClick={reset}>Fit range</Button><Button variant="outline" disabled={!selectedAtom} onClick={()=>selectedAtom&&focus(selectedAtom)}>Focus atom</Button><Button variant="outline" onClick={()=>setExpanded(!expanded)}>{expanded?'Normal view':'Expand view'}</Button><label>Zoom {zoom.toFixed(1)}×<input type="range" min=".25" max="12" step=".05" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label>Atom size<input type="range" min=".5" max="2" step=".1" value={size} onChange={e=>setSize(+e.target.value)}/></label><label><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/> All atom labels</label></div>
 {modification&&<div className="modification-selection" style={{borderColor:modColor}}><strong style={{color:modColor}}>◆ {modification.name} · residue {modification.residue}</strong><div className="protein-controls"><Button variant="outline" onClick={()=>{const a=atoms.find(a=>a.id===(modification.attachment_atom_id||modification.atom_ids?.[0]))||atoms.find(a=>a.residue===modification.residue);if(a)focus(a);}}>Focus modification</Button><label><input type="checkbox" checked={isolate} onChange={e=>setIsolate(e.target.checked)}/> Isolate modified residue</label><label><input type="checkbox" checked={showModification} onChange={e=>setShowModification(e.target.checked)}/> Highlight component</label></div><p>{component.size?'Colored halos identify modification atoms; blue ring identifies the residue attachment atom.':'Dashed rings mark the annotated residue only. Modification atoms have not been supplied.'}</p></div>}
 <p>Click an atom to inspect it; double-click to focus. Drag to rotate, Shift-drag to pan, scroll or pinch to zoom. Keyboard: arrows rotate, +/− zoom, Home fits the range.</p>
 <div className="protein-inspection-layout"><svg ref={svg} className="protein-scene" viewBox="0 0 900 460" tabIndex={0} role="group" aria-label="Interactive atomic structure" onDoubleClick={e=>{if(!gesture.current.downAtom&&e.target===e.currentTarget)setZoom(z=>Math.min(12,z*1.5));}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'].includes(e.key))e.preventDefault();if(e.key==='Home')reset();else if(e.key==='+'||e.key==='=')setZoom(z=>Math.min(12,z*1.2));else if(e.key==='-')setZoom(z=>Math.max(.25,z/1.2));else if(e.key.startsWith('Arrow'))setRotation(([x,y])=>[x+(e.key==='ArrowLeft'?-.1:e.key==='ArrowRight'?.1:0),y+(e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0)]);}}
 onPointerDown={e=>{gesture.current.points.set(e.pointerId,{x:e.clientX,y:e.clientY});gesture.current.moved=false;gesture.current.downAtom=(e.target as Element).closest('[data-atom]')?.getAttribute('data-atom')||'';e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerMove={e=>{const g=gesture.current,old=g.points.get(e.pointerId);if(!old)return;const dx=e.clientX-old.x,dy=e.clientY-old.y;if(Math.abs(dx)+Math.abs(dy)>2)g.moved=true;if(g.points.size===2){const other=[...g.points.entries()].find(([id])=>id!==e.pointerId)![1];const before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y);if(before>1)setZoom(z=>Math.min(12,Math.max(.25,z*after/before)));}else if(e.shiftKey){const rect=e.currentTarget.getBoundingClientRect();setPan(([x,y])=>[x+dx*900/rect.width,y+dy*460/rect.height]);}else setRotation(([x,y])=>[x+dx*.008,y+dy*.008]);g.points.set(e.pointerId,{x:e.clientX,y:e.clientY});}}
 onPointerUp={e=>{const g=gesture.current;if(!g.moved&&g.points.size===1&&g.downAtom){const a=atomMap.get(g.downAtom);if(a){const now=Date.now();if(g.lastAtom===a.id&&now-g.lastClick<350)focus(a);else inspect(a);g.lastAtom=a.id;g.lastClick=now;}}g.points.delete(e.pointerId);e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={e=>gesture.current.points.delete(e.pointerId)}>
 {data.bonds.map((b,i)=>{const a=map.get(b.a),c=map.get(b.b);return a&&c?<g key={i}>{Array.from({length:b.order},(_,j)=><line key={j} x1={a.px+(j-(b.order-1)/2)*3} y1={a.py} x2={c.px+(j-(b.order-1)/2)*3} y2={c.py} stroke={showModification&&component.has(b.a)&&component.has(b.b)?modColor:showModification&&((component.has(b.a)&&b.b===modification?.attachment_atom_id)||(component.has(b.b)&&b.a===modification?.attachment_atom_id))?'#7dd3fc':b.a===selected||b.b===selected?'#f8fafc':'#657f95'} strokeWidth="2"/>)}</g>:null;})}
 {interactions.map((i,j)=>{const a=map.get(i.a)!,b=map.get(i.b)!;return <line key={j} x1={a.px} y1={a.py} x2={b.px} y2={b.py} stroke="#fbbf24" strokeDasharray="5 5"><title>{i.type}: {i.evidence}</title></line>;})}
 {[...points].sort((a,b)=>a.depth-b.depth).map(a=><g key={a.id} data-atom={a.id} role="button" tabIndex={a.id===selected?0:-1} aria-label={`${a.id}, ${a.element}, residue ${a.residue}`} onClick={()=>{if(!gesture.current.moved)inspect(a);}} onDoubleClick={e=>{e.stopPropagation();focus(a);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect(a);}}}>{showModification&&(component.has(a.id)||a.id===modification?.attachment_atom_id||(!component.size&&a.residue===modification?.residue))&&<circle cx={a.px} cy={a.py} r={Math.min(14,Math.max(3,3+zoom))*size+6} fill="none" stroke={a.id===modification?.attachment_atom_id?'#7dd3fc':modColor} strokeWidth="3" strokeDasharray={!component.size?'4 3':undefined}/> }<circle cx={a.px} cy={a.py} r={Math.min(14,Math.max(3,3+zoom))*size} fill={COLORS[a.element]||'#c084fc'} stroke={a.id===selected?'white':'#061525'} strokeWidth={a.id===selected?3:1}/><title>{a.id} · {a.element} · {AMINO[data.sequence[a.residue-1]][0]} {a.residue}</title>{(labels||a.id===selected||(showModification&&component.has(a.id)))&&<text x={a.px+10} y={a.py-9} fill="white" fontSize="14">{a.id}</text>}</g>)}
 </svg><aside className="protein-atom-details"><h3>Atom inspector</h3><label>Select atom<select value={selectedAtom?.id||''} onChange={e=>{const a=atomMap.get(e.target.value);if(a)inspect(a);}}><option value="">Choose an atom</option>{atoms.map(a=><option key={a.id} value={a.id}>{a.id} · {a.element} · residue {a.residue}</option>)}</select></label>{selectedAtom?<><h4>{selectedAtom.name} · {selectedAtom.element}</h4>{component.has(selectedAtom.id)&&<p style={{color:modColor}}>◆ Modification component: {modification?.name}</p>}{selectedAtom.id===modification?.attachment_atom_id&&<p style={{color:'#7dd3fc'}}>Attachment atom on the original residue</p>}<p>{AMINO[data.sequence[selectedAtom.residue-1]][0]} {selectedAtom.residue}</p><dl>{['x','y','z'].map(k=><div key={k}><dt>{k}</dt><dd>{selectedAtom[k as 'x'|'y'|'z'].toFixed(3)} {data.unit}</dd></div>)}</dl><h4>Explicit bonds ({bonded.length})</h4>{bonded.map((b,i)=><p key={i}>{b.a===selected?b.b:b.a} · order {b.order}{!atomMap.has(b.a===selected?b.b:b.a)&&' · outside range'}</p>)}<h4>Nearest displayed atoms</h4>{nearby.map(({a,d})=><button key={a.id} onClick={()=>inspect(a)}>{a.id}: {d.toFixed(2)} {data.unit}</button>)}<p>Proximity is not evidence of a chemical interaction.</p>{data.modifications.filter(m=>m.residue===selectedAtom.residue).map((m,i)=><p key={i}>{m.name}: {m.evidence}</p>)}</>:<p>Select an atom in the picture or the menu to see coordinates, residue identity, bonds and nearby atoms.</p>}</aside></div>
 <label>Interaction overlay<select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>None</option>{[...new Set(data.interactions.map(i=>i.type))].map(t=><option key={t}>{t}</option>)}</select></label><p>C gray · N blue · O pink · S yellow · P orange. Solid lines are supplied bonds; gold dashed lines are annotations. {data.provenance}</p></div>;
}
