"use client";
import {useRef,useState} from 'react';
import {Button} from './ui/button';
import {genotypeBases,parseRegionalReference,parseRegionalVariant,readRegionalVcfHeader,regionalVcfLines,type RegionalReference,type RegionalVariant} from '@/lib/regional-genome';
export function RegionalGenomeReader(){
 const [reference,setReference]=useState<RegionalReference|null>(null),[offset,setOffset]=useState(0);
 const [file,setFile]=useState<File|null>(null),[header,setHeader]=useState<{meta:string[];samples:string[]}|null>(null);
 const [chosen,setChosen]=useState<string[]>([]),[search,setSearch]=useState('');
 const [chrom,setChrom]=useState('chr15'),[start,setStart]=useState('48100000'),[end,setEnd]=useState('48160000');
 const [rows,setRows]=useState<RegionalVariant[]>([]),[result,setResult]=useState<{samples:string[];meta:string[];label:string}|null>(null);
 const [page,setPage]=useState(0),[selected,setSelected]=useState<RegionalVariant|null>(null);
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[progress,setProgress]=useState(0),[error,setError]=useState('');
 const abort=useRef<AbortController|null>(null);
 function fail(e:unknown){setError(e instanceof Error?e.message:'Unable to read this file.');}
 async function openVcf(f:File){const controller=new AbortController();abort.current=controller;setBusy(true);setError('');setHeader(null);setFile(null);setRows([]);setResult(null);setSelected(null);try{const h=await readRegionalVcfHeader(f,controller.signal);setFile(f);setHeader(h);setChosen(h.samples.slice(0,12));setStatus(`${h.samples.length.toLocaleString()} samples available. Choose up to 24 to display; all remain in the source file.`);}catch(e){fail(e);}finally{setBusy(false);}}
 async function scan(){if(!file||!header)return;
  if(!chrom.trim()||!Number.isInteger(+start)||!Number.isInteger(+end)||+start<1||+end<+start||+end-+start>=1_000_000||!chosen.length){setError('Choose a chromosome, a 1-based range of up to 1,000,000 bases, and 1–24 samples.');return;}
  const controller=new AbortController();abort.current=controller;setBusy(true);setError('');setProgress(0);setStatus('Scanning file locally…');setRows([]);setResult(null);setSelected(null);
  const indices=chosen.map(id=>header.samples.indexOf(id));const found:RegionalVariant[]=[];let retained=0,last=0;
  try{for await(const line of regionalVcfLines(file,controller.signal,n=>{if(Date.now()-last>250){setProgress(n/file.size);last=Date.now();}})){
   if(line.startsWith('#'))continue;const first=line.indexOf('\t'),second=line.indexOf('\t',first+1);if(line.slice(0,first)!==chrom.trim())continue;const pos=Number(line.slice(first+1,second));if(pos<+start||pos>+end)continue;
   const row=parseRegionalVariant(line,indices,header.samples.length);retained+=row.line.length;
   if(found.length>=20000||retained>20*1024*1024)throw new Error('Selected results exceed 20,000 variants or 20 MiB. Narrow the region or choose fewer samples; no partial result was imported.');found.push(row);
  }
  found.sort((a,b)=>a.position-b.position);setRows(found);setResult({samples:[...chosen],meta:header.meta,label:`${file.name} · ${chrom}:${start}–${end}`});setPage(0);setSelected(found[0]??null);setProgress(1);setStatus(found.length?`Scan complete: ${found.length.toLocaleString()} variant records for ${chosen.length} selected samples.`:'Scan complete: no variant records matched. Check the chromosome spelling and region; this does not prove every base was confidently called.');
  }catch(e){if(controller.signal.aborted)setStatus('Scan cancelled. No partial results imported.');else fail(e);}finally{setBusy(false);}
 }
 function download(){if(!result)return;const body=[...result.meta,'#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\t'+result.samples.join('\t'),...rows.map(r=>r.line)].join('\n')+'\n';const url=URL.createObjectURL(new Blob([body],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='selected-region.vcf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const contextIndex=reference&&selected?selected.position-reference.start:-1;
 const within=!!reference&&contextIndex>=0&&contextIndex+ (selected?.ref.length??0)<=reference.sequence.length;
 const mismatch=within&&selected&&reference!.sequence.slice(contextIndex,contextIndex+selected.ref.length)!==selected.ref;
 return <section className="module-data" id="regional-genome-reader"><div className="data-section-title"><div><h2>Regional reference &amp; large VCF reader</h2><p className="data-help">Open a single reference FASTA and local .vcf / .vcf.gz files, including BGZF. Files stay on your computer. Compressed files are scanned sequentially in chunks; index files are not used yet.</p></div></div>
 <div className="data-samples"><article><h3>1. Reference DNA</h3><label className="data-label">Regional FASTA (up to 1 million bases)<input disabled={busy} type="file" accept=".fa,.fasta,.fna" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setError('');try{if(f.size>3*1024*1024)throw new Error('Choose a regional FASTA under 3 MiB.');const r=parseRegionalReference(await f.text());setReference(r);setOffset(0);setStart(String(r.start));setEnd(String(r.end));}catch(err){fail(err);}e.target.value='';}}/></label><p className="data-help">NCBI headers such as NC_000015.10:48100000-48160000 supply the genomic start. Otherwise enter the correct reference start below.</p>{reference&&<><strong>{reference.id} · {reference.sequence.length.toLocaleString()} bases</strong><label className="data-label">Reference genomic start<input type="number" min={1} value={reference.start} onChange={e=>{const n=+e.target.value;if(Number.isSafeInteger(n)&&n>0)setReference({...reference,start:n,end:n+reference.sequence.length-1});}}/></label><label className="data-label">Browse reference position<input type="range" min={0} max={Math.max(0,reference.sequence.length-100)} value={offset} onChange={e=>setOffset(+e.target.value)}/></label><p>{reference.start+offset}–{Math.min(reference.end,reference.start+offset+99)}</p><code style={{display:'block',overflowWrap:'anywhere',whiteSpace:'normal'}}>{reference.sequence.slice(offset,offset+100)}</code></>}</article>
 <article><h3>2. VCF and samples</h3><label className="data-label">Select chromosome VCF or VCF.gz<input type="file" disabled={busy} accept=".vcf,.gz,.bgz" onChange={e=>{const f=e.target.files?.[0];if(f)void openVcf(f);e.target.value='';}}/></label>{file&&<p>{file.name} · {(file.size/1024/1024).toFixed(1)} MiB</p>}{header&&<><label className="data-label">Find sample<input value={search} disabled={busy} onChange={e=>setSearch(e.target.value)} placeholder="Sample ID"/></label><p>{chosen.length}/24 selected out of {header.samples.length.toLocaleString()}. First 12 selected for convenience, not population representation.</p><Button variant="outline" disabled={busy} onClick={()=>setChosen([])}>Clear selection</Button><div style={{maxHeight:160,overflow:'auto'}}>{header.samples.filter(s=>s.toLowerCase().includes(search.toLowerCase())).slice(0,100).map(s=><label key={s} style={{display:'block'}}><input type="checkbox" checked={chosen.includes(s)} disabled={busy||chosen.length>=24&&!chosen.includes(s)} onChange={e=>setChosen(e.target.checked?[...chosen,s]:chosen.filter(x=>x!==s))}/> {s}</label>)}</div><small>Showing up to 100 matching sample IDs. Search to find any sample.</small></>}</article></div>
 <div className="data-section-title" style={{flexWrap:'wrap',gap:12}}><label className="data-label">VCF chromosome<input disabled={busy} value={chrom} onChange={e=>setChrom(e.target.value)}/></label><label className="data-label">Start (inclusive)<input disabled={busy} type="number" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="data-label">End (inclusive)<input disabled={busy} type="number" value={end} onChange={e=>setEnd(e.target.value)}/></label><Button disabled={busy||!header} onClick={()=>void scan()}>Scan selected region</Button>{busy&&<Button variant="outline" onClick={()=>abort.current?.abort()}>Cancel</Button>}</div>
 <p className="data-help">Use the exact VCF chromosome name (chr15, 15, or an accession). Confirm that FASTA and VCF use the same assembly. Selection includes records whose POS is inside the interval; overlapping variants that start outside it are not included.</p>{busy&&<progress aria-label="VCF scan progress" max={1} value={progress} style={{width:'100%'}}/>}<p role="status">{status}</p>{error&&<p role="alert" className="data-notice">{error}</p>}
 {result&&<><p>{result.label}</p><Button disabled={!rows.length} variant="outline" onClick={download}>Download selected VCF</Button><p className="data-help">Export keeps source INFO fields (including cohort-wide counts); these are not recalculated for selected samples. Genotypes show observed calls: | is phased, / is unphased, ? is missing. No haplotype sequence or clinical interpretation is inferred.</p><div style={{overflow:'auto',maxHeight:480}}><table><thead><tr><th>Position</th><th>ID</th><th>REF → ALT</th>{result.samples.map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rows.slice(page*50,page*50+50).map((r,i)=><tr key={i}><td><button className="data-open" onClick={()=>setSelected(r)}>{r.position}</button></td><td>{r.id}</td><td>{r.ref} → {r.alt}</td>{r.calls.map((c,j)=><td key={j} style={{padding:8,whiteSpace:'nowrap'}} title={c}>{genotypeBases(c,r.ref,r.alt)}</td>)}</tr>)}</tbody></table></div>{rows.length>0&&<div className="data-section-title"><Button variant="outline" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page+1} / {Math.ceil(rows.length/50)}</span><Button variant="outline" disabled={(page+1)*50>=rows.length} onClick={()=>setPage(page+1)}>Next</Button></div>}</>}
 {selected&&<div className="data-notice"><h3>{selected.chrom}:{selected.position} · {selected.ref} → {selected.alt}</h3>{!reference?<p>Load matching reference DNA to view surrounding sequence.</p>:!within?<p>This position is outside the loaded reference span. Check the FASTA start and genome assembly.</p>:<><p>{mismatch?'Reference allele mismatch: do not combine these records until the reference and coordinates are corrected.':'REF matches at this position. This alone does not verify the genome assembly; confirm source metadata.'}</p><code style={{overflowWrap:'anywhere'}}>{reference.sequence.slice(Math.max(0,contextIndex-20),contextIndex)}<mark>{reference.sequence.slice(contextIndex,contextIndex+selected.ref.length)}</mark>{reference.sequence.slice(contextIndex+selected.ref.length,contextIndex+selected.ref.length+20)}</code></>}</div>}
 </section>;
}
