import { proteinSample, proteinTeachingSamples } from './protein-structure';
import { HIERARCHY_TEMPLATES } from "./hierarchy-data";
export type DataCategory = 'genome' | 'epigenome' | 'transcriptome' | 'singlecell' | 'proteome' | 'metabolome' | 'immunomics' | 'imaging' | 'pathways' | 'evolution' | 'multiomics';
export type DataTemplate = { id: string; category: DataCategory; title: string; filename: string; description: string; columns?: string[]; content: string; units: string; };
export const CATEGORY_LABELS: Record<DataCategory, string> = {
  genome: 'Genome & variants', epigenome: 'Epigenome & Hi-C', transcriptome: 'Transcriptome', singlecell: 'Single cell & spatial', proteome: 'Proteome & structures', metabolome: 'Metabolites, lipids & glycans', immunomics: 'Immune repertoire', imaging: 'Imaging & cytometry', pathways: 'Pathways', evolution: 'Cell evolution', multiomics: 'Multi-omics evidence',
};
export const TEMPLATES: DataTemplate[] = [
  ...HIERARCHY_TEMPLATES,
  ...proteinTeachingSamples().slice(1).map((sample,i)=>({id:'protein-teaching-'+i,category:'proteome' as const,title:i===0?'100-residue structure & modification teaching set':'Sequence-only structure teaching set',filename:i===0?'protein_teaching_100.json':'protein_teaching_missing.json',description:sample.provenance,units:'Schematic coordinates',content:JSON.stringify(sample,null,2)+'\n'})),
  {id:'protein-atomic-bundle',category:'proteome',title:'Peptide atoms, modifications & motion',filename:'protein_structure.json',description:'Synthetic backbone atoms, annotation examples and illustrative coordinate frames. No physical simulation.',units:'Schematic coordinates and illustrative steps',content:JSON.stringify(proteinSample(),null,2)+'\n'},
  {id:'alignment',category:'genome',title:'Aligned DNA',filename:'aligned_dna.fasta',description:'Three aligned sequences ready for DNA analysis.',units:'1-based alignment columns',content:'>reference\nATGGCTGAATTTCCGAAAGGTTACTGGAAC\n>sample_A\nATGGCTGAATTTCCAAAAGGTTACTGGAAC\n>sample_B\nATGGCTGAGTTTCCGAAAGGTTACTGGAAC\n'},
  {id:'reads',category:'genome',title:'Sequencing reads',filename:'reads.fastq',description:'Two four-line FASTQ reads with quality scores.',units:'Phred+33 example',content:'@read_1\nACGTACGT\n+\nIIIIIIII\n@read_2\nACGTTCGT\n+\nIIIIHIII\n'},
  {id:'variants',category:'genome',title:'Variant calls',filename:'variants.vcf',description:'Synthetic variants on an artificial demo chromosome.',units:'1-based positions; assembly: demo',content:'##fileformat=VCFv4.2\n##contig=<ID=demo,length=1000>\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\ndemo\t20\t.\tA\tG\t60\tPASS\t.\ndemo\t40\t.\tC\tT\t50\tPASS\t.\n'},
  {id:'intervals',category:'genome',title:'Genome intervals',filename:'intervals.bed',description:'Two named intervals on an artificial chromosome.',units:'0-based, half-open; assembly: demo',content:'demo\t0\t30\tpromoter\ndemo\t50\t90\texon\n'},
  {id:'haplotypes',category:'genome',title:'Phased haplotypes',filename:'haplotypes.tsv',description:'Processed phased genotype table; no phasing is computed.',columns:['sample','chrom','position','haplotype_1','haplotype_2'],units:'1-based; assembly: demo',content:'sample\tchrom\tposition\thaplotype_1\thaplotype_2\nS1\tdemo\t20\tA\tG\nS1\tdemo\t40\tC\tT\nS2\tdemo\t20\tA\tA\n'},
  {id:'methylation',category:'epigenome',title:'DNA methylation',filename:'methylation.tsv',description:'Per-feature methylation beta values.',columns:['feature','sample','beta'],units:'Beta: 0–1',content:'feature\tsample\tbeta\npromoter_A\tcontrol\t0.18\npromoter_A\tcase\t0.78\npromoter_B\tcontrol\t0.42\npromoter_B\tcase\t0.36\n'},
  {id:'accessibility',category:'epigenome',title:'Chromatin accessibility',filename:'accessibility.tsv',description:'Processed ATAC-style peak signal.',columns:['chrom','start','end','signal'],units:'0-based, half-open; arbitrary signal',content:'chrom\tstart\tend\tsignal\ndemo\t0\t100\t12\ndemo\t100\t200\t25\ndemo\t200\t300\t8\n'},
  {id:'contacts',category:'epigenome',title:'Hi-C contact export',filename:'hic_contacts.tsv',description:'Sparse binned contact counts; not a .hic/.cool binary file.',columns:['bin_1','bin_2','count'],units:'Demo bin IDs; raw counts',content:'bin_1\tbin_2\tcount\n1\t1\t80\n1\t2\t30\n1\t3\t8\n2\t2\t72\n2\t3\t25\n3\t3\t67\n'},
  {id:'expression',category:'transcriptome',title:'RNA expression',filename:'expression.csv',description:'Small gene-by-sample count matrix.',columns:['gene','control','case'],units:'Raw integer counts; not normalized',content:'gene,control,case\nTP53,120,85\nEGFR,40,180\nMYC,30,140\nBRCA1,60,55\n'},
  {id:'isoforms',category:'transcriptome',title:'Isoform abundance',filename:'isoforms.tsv',description:'Processed transcript abundance for two samples.',columns:['transcript','gene','sample','tpm'],units:'TPM',content:'transcript\tgene\tsample\ttpm\nTX_A1\tGENE_A\tcontrol\t12\nTX_A2\tGENE_A\tcontrol\t4\nTX_A1\tGENE_A\tcase\t6\nTX_A2\tGENE_A\tcase\t18\n'},
  {id:'cells',category:'singlecell',title:'Cell embedding',filename:'cell_embedding.csv',description:'Precomputed illustrative coordinates and cluster labels.',columns:['cell_id','x','y','cluster'],units:'Arbitrary embedding coordinates; not computed UMAP',content:'cell_id,x,y,cluster\ncell_1,1.2,2.3,T-cell\ncell_2,1.5,2.1,T-cell\ncell_3,4.2,5.1,B-cell\ncell_4,4.5,5.3,B-cell\n'},
  {id:'spatial',category:'singlecell',title:'Spatial spots',filename:'spatial_spots.tsv',description:'Spot coordinates and a marker value.',columns:['spot','x','y','gene','expression'],units:'Micrometres; arbitrary expression',content:'spot\tx\ty\tgene\texpression\nspot_1\t0\t0\tCD3D\t4\nspot_2\t100\t0\tCD3D\t7\nspot_3\t0\t100\tCD3D\t2\n'},
  {id:'proteins',category:'proteome',title:'Protein abundance',filename:'protein_abundance.tsv',description:'Processed relative protein intensities.',columns:['protein','control','case'],units:'Arbitrary intensity',content:'protein\tcontrol\tcase\nEGFR\t1500\t4200\nTP53\t2100\t1800\nACTB\t8000\t7900\n'},
  {id:'spectrum',category:'proteome',title:'MS/MS peaks',filename:'msms_peaks.tsv',description:'Centroided peak list for a teaching spectrum.',columns:['mz','intensity'],units:'m/z; arbitrary intensity',content:'mz\tintensity\n147.1128\t210000\n227.1026\t175000\n276.1554\t390000\n391.1823\t520000\n504.2664\t650000\n'},
  {id:'ptm',category:'proteome',title:'Protein modifications',filename:'protein_ptm.tsv',description:'Processed site-level modification table.',columns:['protein','residue','modification','fold_change'],units:'1-based residues; case/control ratio',content:'protein\tresidue\tmodification\tfold_change\nEGFR\tY1068\tphosphorylation\t3.4\nTP53\tS15\tphosphorylation\t1.8\n'},
  {id:'metabolites',category:'metabolome',title:'Metabolite features',filename:'metabolite_features.csv',description:'Processed LC-MS features with candidate annotations.',columns:['feature','mz','rt_min','intensity','candidate'],units:'m/z; minutes; arbitrary intensity',content:'feature,mz,rt_min,intensity,candidate\nF1,87.0088,1.8,380000,Pyruvate\nF2,89.0244,3.2,720000,Lactate\nF3,191.0197,6.5,510000,Citrate\n'},
  {id:'lipids',category:'metabolome',title:'Lipid abundance',filename:'lipids.tsv',description:'Processed lipid-class abundance examples.',columns:['lipid','sample','abundance'],units:'Relative abundance',content:'lipid\tsample\tabundance\nPC 16:0_18:1\tcontrol\t12\nPC 16:0_18:1\tcase\t18\nSM d18:1_16:0\tcontrol\t9\nSM d18:1_16:0\tcase\t7\n'},
  {id:'glycans',category:'metabolome',title:'Glycan compositions',filename:'glycans.tsv',description:'Composition annotations, not resolved glycan structures.',columns:['composition','sample','abundance'],units:'Relative abundance',content:'composition\tsample\tabundance\nHex5HexNAc2\tcontrol\t15\nHex5HexNAc2\tcase\t21\nHex6HexNAc2\tcontrol\t8\n'},
  {id:'airr',category:'immunomics',title:'Repertoire export',filename:'repertoire.tsv',description:'AIRR-inspired subset; not full AIRR schema validation.',columns:['sequence_id','junction_aa','v_call','j_call','duplicate_count'],units:'Clonotype counts',content:'sequence_id\tjunction_aa\tv_call\tj_call\tduplicate_count\nclone_1\tCASSIRSSYEQYF\tTRBV19\tTRBJ2-7\t128\nclone_2\tCASSLGQGNEQFF\tTRBV7-9\tTRBJ2-1\t86\n'},
  {id:'cytometry',category:'imaging',title:'Cytometry events',filename:'cytometry_events.csv',description:'Processed event intensities exported from an FCS workflow.',columns:['event','CD3','CD4','CD8'],units:'Arbitrary fluorescence; uncompensated teaching values',content:'event,CD3,CD4,CD8\n1,850,700,20\n2,820,30,650\n3,15,12,8\n'},
  {id:'imagefeatures',category:'imaging',title:'Image measurements',filename:'image_measurements.tsv',description:'Segmented-cell measurements, not an image file.',columns:['cell','area_um2','mean_intensity'],units:'Square micrometres; arbitrary intensity',content:'cell\tarea_um2\tmean_intensity\nC1\t85\t125\nC2\t120\t180\nC3\t95\t142\n'},
  {id:'network',category:'pathways',title:'Interaction edges',filename:'network_edges.tsv',description:'Illustrative directed interactions.',columns:['source','target','relationship'],units:'Categorical relationships',content:'source\ttarget\trelationship\nEGFR\tGRB2\trecruitment\nGRB2\tSOS1\trecruitment\nSOS1\tKRAS\tactivation\n'},
  {id:'clones',category:'evolution',title:'Clone fractions',filename:'clone_fractions.tsv',description:'Processed clone fractions; no tree inference.',columns:['clone','parent','fraction'],units:'Fraction: 0–1',content:'clone\tparent\tfraction\nancestor\tnone\t0.3\nclone_A\tancestor\t0.45\nclone_B\tancestor\t0.25\n'},
  {id:'integration',category:'multiomics',title:'Multi-omics evidence',filename:'multiomics_evidence.tsv',description:'Long-form evidence with explicit units per row.',columns:['sample','feature','layer','value','unit'],units:'Mixed; see unit column',content:'sample\tfeature\tlayer\tvalue\tunit\ncase\tEGFR\tRNA\t320\tTPM\ncase\tEGFR\tprotein\t2.8\tfold_change\ncase\tEGFR\tcopy_number\t6\tcopies\n'},
];
export const EXTERNAL_FORMATS = [
  { extensions: ['bam','cram','bcf'], category:'genome', tool:'SAMtools/BCFtools', action:'Export aligned FASTA, VCF text, or a processed interval table. CRAM also needs its matching reference.' },
  { extensions: ['bw','bigwig','bb','bigbed'], category:'epigenome', tool:'UCSC utilities or pyBigWig', action:'Export a BED/bedGraph or signal TSV for the interval of interest.' },
  { extensions: ['hic','cool','mcool'], category:'epigenome', tool:'Cooler or Juicer', action:'Export a small binned contact table with bin IDs and counts.' },
  { extensions: ['h5ad','h5','loom','rds','rdata'], category:'singlecell', tool:'Scanpy/AnnData or Seurat', action:'Export an expression matrix and cell metadata/embedding as CSV or TSV. Keep cell IDs consistent.' },
  { extensions: ['raw','wiff','d','mzml','mzxml','mzidentml','mzid'], category:'proteome', tool:'ProteoWizard and your MS analysis software', action:'Export centroided m/z–intensity peaks, PSMs, or protein abundance as TSV. Raw spectrum decoding is not available here.' },
  { extensions: ['fcs'], category:'imaging', tool:'FlowJo or FlowKit', action:'Export compensated event intensities with marker names as CSV.' },
  { extensions: ['tif','tiff','svs','ndpi','dcm','dicom','zarr','png','jpg','jpeg'], category:'imaging', tool:'QuPath, Fiji, or an OME workflow', action:'Export cell/spot measurements as CSV or TSV. Image rendering and segmentation are not implemented.' },
  { extensions: ['gz','zip','bz2','xz','7z'], category:'genome', tool:'Archive/decompression software', action:'Decompress locally, then select the supported text files. Archives are never executed or expanded by this app.' },
] as const;
