import type { DataTemplate } from './data-catalog';
export const MOLECULE_LOCATIONS: Record<string,string> = {
 dna:'Nucleus and mitochondria in nucleated human cells. Mature red blood cells lack a nucleus and mitochondria.',
 rna:'Nucleus and cytoplasm; mRNA can associate with ribosomes. Mitochondria also contain RNA.',
 protein:'Location depends on the protein: cytoplasm, membranes, nucleus, organelles, or extracellular space.',
 'peptide-ms':'Peptides may be generated by protein digestion during sample preparation; MS peaks are measurements, not molecules with inferred coordinates.',
 metabolite:'Metabolites occupy multiple compartments; localization requires a compartment-specific assay.',
 lipid:'Many lipids occur in cellular and organelle membranes; lipid droplets also store lipids.',
 glycan:'Glycans can be attached to proteins and lipids; processing involves the ER and Golgi.',
};
const samples=[['SYN001','blood_bulk','blood','leukocytes','bulk','not_applicable'],['SYN001','blood_T01','blood','CD4 T cell','single-cell','T01'],['SYN002','liver_bulk','liver','hepatocyte-enriched tissue','bulk','not_applicable']];
const molecules=['dna','rna','protein','peptide-ms','metabolite','lipid','glycan'];
const sequences:Record<string,string>={dna:'ATGGCTGAATTTCCGAAAGGTTACTGGAAC',rna:'AUGGCUGAAUUUCCGAAAGGUUACUGGAAC',protein:'MAEFPKGYWN','peptide-ms':'MAEFPK'};
const structures=['participant_id\tsample_id\tmolecule\tpoint_id\tx\ty\tz\tunit\tresolution'];
const times=['participant_id\tsample_id\tmolecule\ttime_hours\tvalue\tunit'];
for(const [person,sample] of samples)for(const [mi,molecule] of molecules.entries()) {
 // Explicitly schematic point coordinates, not atomic coordinates or predicted folds.
 for(let i=0;i<8;i++)structures.push([person,sample,molecule,String(i+1),(Math.cos(i*.8)*(2+mi*.15)).toFixed(3),(Math.sin(i*.8)*(2+mi*.15)).toFixed(3),(i*.7).toFixed(3),'schematic_units','coarse teaching points'].join('\t'));
 for(const [i,time] of [0,6,12,24].entries())times.push([person,sample,molecule,time,10+mi*4+i*(mi%2?3:1),'arbitrary_units'].join('\t'));
}
export const HIERARCHY_TEMPLATES:DataTemplate[]=[
 {id:'rna-sequence',category:'transcriptome',title:'RNA sequence',filename:'rna_sequence.fasta',description:'Synthetic RNA with U bases; sequence preview, not expression quantification.',units:'1-based nucleotide positions',content:'>synthetic_mRNA\n'+sequences.rna+'\n'},
 {id:'protein-sequence',category:'proteome',title:'Protein sequence',filename:'protein_sequence.fasta',description:'Synthetic amino-acid sequence; no folding prediction.',units:'1-based residue positions',content:'>synthetic_protein\n'+sequences.protein+'\n'},
 {id:'hierarchy-metadata',category:'multiomics',title:'Participant & sample metadata',filename:'hierarchy_metadata.tsv',description:'Two fictional participants, blood/liver specimens, single-cell and bulk assays.',columns:['participant_id','sample_id','tissue','cell_type','assay_mode','cell_id'],units:'Categorical metadata; synthetic participants',content:'participant_id\tsample_id\ttissue\tcell_type\tassay_mode\tcell_id\n'+samples.map(s=>s.join('\t')).join('\n')+'\n'},
 {id:'hierarchy-sequences',category:'multiomics',title:'Linked molecular sequences',filename:'hierarchy_sequences.tsv',description:'DNA, RNA, protein and peptide records linked by participant and sample IDs.',columns:['participant_id','sample_id','molecule','sequence'],units:'DNA/RNA nucleotides or protein residues; synthetic',content:'participant_id\tsample_id\tmolecule\tsequence\n'+samples.flatMap(([p,s])=>Object.entries(sequences).map(([m,q])=>[p,s,m,q].join('\t'))).join('\n')+'\n'},
 {id:'hierarchy-coordinates',category:'multiomics',title:'3D schematic coordinates',filename:'hierarchy_coordinates.tsv',description:'Synthetic coarse points for seven molecule layers. Not atoms or experimentally resolved structures.',columns:['participant_id','sample_id','molecule','point_id','x','y','z','unit','resolution'],units:'Schematic units; no physical length or inferred bonds',content:structures.join('\n')+'\n'},
 {id:'hierarchy-time',category:'multiomics',title:'Molecular time course',filename:'hierarchy_timecourse.tsv',description:'Four synthetic measurement times for seven molecule layers; not a moving molecular trajectory.',columns:['participant_id','sample_id','molecule','time_hours','value','unit'],units:'Hours; arbitrary measurement units',content:times.join('\n')+'\n'},
];
export type DataRows={id:string;name:string;status:string;source:string;headers:string[];rows:string[][];rowCount:number};
export type JoinedRow=Record<string,string>;
export function rowsWithColumns(datasets:DataRows[],columns:string[]):JoinedRow[]{
 return datasets.filter(d=>d.status==='ready'&&columns.every(c=>d.headers.includes(c))).flatMap(d=>d.rows.map(row=>({...Object.fromEntries(d.headers.map((h,i)=>[h,row[i]??''])),_file:d.name,_origin:d.source,_dataset:d.id})));
}
export function sameSample(row:JoinedRow,metadata:JoinedRow,molecule?:string){return row.participant_id===metadata.participant_id&&row.sample_id===metadata.sample_id&&(!molecule||row.molecule===molecule);}
export function finiteCoordinate(row:JoinedRow){return ['x','y','z'].every(k=>row[k]?.trim()!==''&&Number.isFinite(Number(row[k])));}
