export const AMINO:Record<string,[string,string,string]>={A:['Alanine','CH3','nonpolar'],R:['Arginine','(CH2)3–NH–C(=NH)–NH2','basic'],N:['Asparagine','CH2–C(=O)–NH2','polar'],D:['Aspartate','CH2–COOH','acidic'],C:['Cysteine','CH2–SH','polar'],E:['Glutamate','(CH2)2–COOH','acidic'],Q:['Glutamine','(CH2)2–C(=O)–NH2','polar'],G:['Glycine','H','nonpolar'],H:['Histidine','CH2–imidazole','basic'],I:['Isoleucine','CH(CH3)–CH2–CH3','nonpolar'],L:['Leucine','CH2–CH(CH3)2','nonpolar'],K:['Lysine','(CH2)4–NH2','basic'],M:['Methionine','CH2–CH2–S–CH3','nonpolar'],F:['Phenylalanine','CH2–phenyl','aromatic'],P:['Proline','(CH2)3 ring to backbone N','nonpolar'],S:['Serine','CH2–OH','polar'],T:['Threonine','CH(OH)–CH3','polar'],W:['Tryptophan','CH2–indole','aromatic'],Y:['Tyrosine','CH2–phenyl–OH','aromatic'],V:['Valine','CH(CH3)2','nonpolar']};
export const MODIFICATIONS=[['Phosphorylation','STY','Phosphate ester; site and localization evidence required'],['Acetylation','K','Acetyl group on lysine amino group; N-terminal acetylation also occurs'],['Methylation','KR','One or more methyl groups; specify degree'],['Oxidation','M','Methionine sulfoxide; may arise during preparation'],['N-linked glycosylation','N','Asparagine-linked glycan; composition does not specify topology'],['O-linked glycosylation','ST','O-linked glycan; composition and linkage needed'],['Ubiquitination','K','Isopeptide linkage to ubiquitin; topology must be supplied'],['SUMOylation','K','SUMO conjugation via isopeptide linkage'],['S-palmitoylation','C','Thioester-linked fatty acyl group'],['Disulfide formation','C','Covalent S–S bond between two cysteines'],['Deamidation','NQ','Conversion of side-chain amide; may be an artifact'],['Hydroxylation','PK','Hydroxyl group; specify exact atom'],['S-nitrosylation','C','S–NO group'],['Citrullination','R','Arginine converted to citrulline'],['Carbamidomethylation','C','Common sample-preparation alkylation, not a physiological PTM']];
export type Atom={id:string;residue:number;name:string;element:string;x:number;y:number;z:number};
export type Structure={reference:string;sequence:string;provenance:string;unit:'angstrom'|'schematic';atoms:Atom[];bonds:{a:string;b:string;order:number}[];modifications:{residue:number;name:string;evidence:string;atom_ids?:string[];attachment_atom_id?:string}[];interactions:{a:string;b:string;type:string;evidence:string}[];frames:{time:number;positions:number[][]}[];timeUnit:string};
export function validateStructure(raw:unknown):Structure {
 const d=raw as Structure;const fail=(s:string):never=>{throw Error(s);};
 if(!d||!d.reference||!d.provenance||!d.sequence||!(/^[ACDEFGHIKLMNPQRSTVWY]+$/).test(d.sequence)||d.sequence.length>500)fail('Provide reference, provenance and a sequence of 1–500 standard amino acids.');
 if(!['angstrom','schematic'].includes(d.unit)||!Array.isArray(d.atoms)||d.atoms.length>5000)fail('Use angstrom or schematic units and at most 5,000 atoms.');
 const ids=new Set<string>();for(const a of d.atoms){if(!a.id||ids.has(a.id)||!a.name||!['C','N','O','S','H','P','Se','Zn','Fe','Mg','Ca','F','Cl','Br','I'].includes(a.element)||!Number.isInteger(a.residue)||a.residue<1||a.residue>d.sequence.length||![a.x,a.y,a.z].every(n=>Number.isFinite(n)&&Math.abs(n)<1e5))fail('Invalid or duplicate atom, residue mapping, element, or coordinate.');ids.add(a.id);}
 for(const key of ['bonds','modifications','interactions','frames'] as const)if(!Array.isArray(d[key]))fail('Missing array: '+key);
 if(d.bonds.length>10000||d.interactions.length>10000||d.modifications.length>5000||d.frames.length>100)fail('Too many annotations or frames (maximum 100 frames).');
 for(const b of d.bonds)if(!ids.has(b.a)||!ids.has(b.b)||b.a===b.b||![1,2,3].includes(b.order))fail('Bonds require two existing atoms and bond order 1, 2, or 3.');
 for(const i of d.interactions)if(!ids.has(i.a)||!ids.has(i.b)||i.a===i.b||!i.type||!i.evidence)fail('Interactions require existing atom IDs, type and evidence.');
 for(const m of d.modifications)if(!Number.isInteger(m.residue)||m.residue<1||m.residue>d.sequence.length||!m.name||!m.evidence)fail('Modification needs a mapped residue, name and evidence.');
 for(const m of d.modifications){if(m.atom_ids!==undefined&&(!Array.isArray(m.atom_ids)||new Set(m.atom_ids).size!==m.atom_ids.length||m.atom_ids.some(id=>!ids.has(id))))fail('Modification atom_ids must be unique existing atom IDs.');if(m.attachment_atom_id!==undefined&&(!ids.has(m.attachment_atom_id)||d.atoms.find(a=>a.id===m.attachment_atom_id)?.residue!==m.residue))fail('Modification attachment must map to its annotated residue.');if(m.attachment_atom_id&&m.atom_ids?.length&&!d.bonds.some(b=>(b.a===m.attachment_atom_id&&m.atom_ids!.includes(b.b))||(b.b===m.attachment_atom_id&&m.atom_ids!.includes(b.a))))fail('Modification attachment needs an explicit bond to a modification atom.');}
 let previous=-Infinity;for(const f of d.frames){if(!Number.isFinite(f.time)||f.time<=previous||f.positions.length!==d.atoms.length||!f.positions.every(p=>Array.isArray(p)&&p.length===3&&p.every(n=>Number.isFinite(n)&&Math.abs(n)<1e5)))fail('Frames need increasing times and finite xyz for every atom, in atom order.');previous=f.time;}
 if(d.frames.length&&!d.timeUnit)fail('Frames require a timeUnit.');return d;
}
export function proteinSample():Structure {
 const sequence='ACDEFGHIKLMNPQRSTVWYAC';const atoms:Atom[]=[];const bonds:Structure['bonds']=[];
 for(let i=0;i<sequence.length;i++){for(const [j,name] of ['N','CA','C','O'].entries()){const a={id:`${i+1}:${name}`,residue:i+1,name,element:name==='CA'?'C':name,x:Math.cos(i*.8)*8+j*.8,y:Math.sin(i*.8)*8+j*.5,z:i*1.6+(j===3?1:0)};atoms.push(a);if(j)bonds.push({a:`${i+1}:${j===3?'C':['N','CA'][j-1]}`,b:a.id,order:j===3?2:1});}if(i)bonds.push({a:`${i}:C`,b:`${i+1}:N`,order:1});}
 return {reference:'synthetic-peptide-21',sequence,provenance:'Synthetic backbone-only teaching geometry. No side-chain atoms, hydrogens, terminal oxygen, or physical simulation. No experimental inference.',unit:'schematic',atoms,bonds,modifications:[{residue:16,name:'Phosphorylation',evidence:'Synthetic annotation at S16; modified atoms not supplied'},{residue:9,name:'Acetylation',evidence:'Synthetic annotation at K9; modified atoms not supplied'}],interactions:[{a:'1:O',b:'5:N',type:'Hydrogen bond',evidence:'Illustrative annotation only; geometry not validated'},{a:'5:C',b:'10:CA',type:'Hydrophobic contact',evidence:'Illustrative annotation only; backbone endpoints represent residues'}],frames:Array.from({length:16},(_,f)=>({time:f,positions:atoms.map(a=>[a.x+Math.sin(f*.3+a.residue*.2)*1.2,a.y+Math.cos(f*.3+a.residue*.2)*1.2,a.z])})),timeUnit:'illustrative step'};
}
export function selectAtoms(d:Structure,start:number,end:number){return d.atoms.filter(a=>a.residue>=start&&a.residue<=end);}

export function residueBoxSize(count:number,width:number,min:number,max:number,mode:string){
 const low=Math.max(28,Math.min(min,max));const high=Math.max(low,max);
 return Math.round(mode==='min'?low:mode==='max'?high:Math.max(low,Math.min(high,(width-Math.max(0,count-1)*5)/Math.max(1,count))));
}
export function proteinTeachingSamples():Structure[]{
 const basic=proteinSample();const extended=proteinSample();extended.reference='synthetic-protein-100';extended.sequence='ACDEFGHIKLMNPQRSTVWY'.repeat(5);extended.atoms=[];extended.bonds=[];
 for(let r=1;r<=100;r++){const template=basic.atoms.filter(a=>a.residue===1);for(const a of template)extended.atoms.push({...a,id:`${r}:${a.name}`,residue:r,x:a.x+Math.sin(r*.35)*10,y:a.y+Math.cos(r*.35)*10,z:a.z+r*1.2});for(const b of basic.bonds.filter(b=>b.a.startsWith('1:')&&b.b.startsWith('1:')))extended.bonds.push({...b,a:b.a.replace('1:',r+':'),b:b.b.replace('1:',r+':')});if(r>1)extended.bonds.push({a:`${r-1}:C`,b:`${r}:N`,order:1});}
 extended.modifications=MODIFICATIONS.map(([name,sites],i)=>({residue:extended.sequence.indexOf(sites[0],Math.floor(i/5)*20)+1,name,evidence:'Synthetic teaching annotation; modification atoms absent. Not an observed site.'}));
 extended.frames=Array.from({length:20},(_,i)=>({time:i,positions:extended.atoms.map(a=>[a.x+Math.sin(i*.2+a.residue*.15),a.y+Math.cos(i*.2+a.residue*.15),a.z])}));
 extended.provenance='Synthetic backbone-only teaching geometry across all 20 standard amino-acid types. All 15 reference modification categories are annotations only. No side-chain atoms, hydrogens, terminal oxygen or physical simulation.';
 const missing:Structure={...basic,reference:'sequence-only-teaching',sequence:'ACDEFGHIKLMNPQRSTVWY',provenance:'Synthetic sequence only. No atom, modification or interaction evidence supplied.',atoms:[],bonds:[],modifications:[],interactions:[],frames:[],timeUnit:''};return [basic,extended,missing];
}
